// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyLeague.Infrastructure.Persistence.Contexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyLeague.Infrastructure.Migrations
{
    [DbContext(typeof(FloorballDbContext))]
    partial class FloorballDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Floorball.EventSourcedFloorballMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("OfficialIdsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScheduledDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<bool>("WentToOvertime")
                        .HasColumnType("boolean");

                    b.Property<bool>("WentToShootout")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("EventSourcedFloorballMatches");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ScheduledDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Venue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("WentToOvertime")
                        .HasColumnType("boolean");

                    b.Property<bool>("WentToShootout")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("SeasonId");

                    b.ToTable("FloorballMatches");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CareerAssists")
                        .HasColumnType("integer");

                    b.Property<int>("CareerGoals")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("FloorballPlayers");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballReferee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LicenseExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LicenseIssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MatchesOfficiated")
                        .HasColumnType("integer");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("FloorballReferees");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballSeason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DivisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FloorballSeasons");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DivisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("HomeArena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrimaryJerseyColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SecondaryJerseyColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TeamCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FloorballTeams");
                });

            modelBuilder.Entity("FloorballMatchOfficial", b =>
                {
                    b.Property<Guid>("MatchesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OfficialsId")
                        .HasColumnType("uuid");

                    b.HasKey("MatchesId", "OfficialsId");

                    b.HasIndex("OfficialsId");

                    b.ToTable("FloorballMatchOfficial");
                });

            modelBuilder.Entity("FloorballSeasonTeam", b =>
                {
                    b.Property<Guid>("SeasonsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamsId")
                        .HasColumnType("uuid");

                    b.HasKey("SeasonsId", "TeamsId");

                    b.HasIndex("TeamsId");

                    b.ToTable("FloorballSeasonTeam");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballMatch", b =>
                {
                    b.HasOne("Domain.Entities.Floorball.FloorballTeam", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Floorball.FloorballTeam", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Floorball.FloorballSeason", "Season")
                        .WithMany("Matches")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsMany("Domain.ValueObjects.Floorball.FloorballPeriodScore", "PeriodScores", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<int>("AwayScore")
                                .HasColumnType("integer");

                            b1.Property<int>("HomeScore")
                                .HasColumnType("integer");

                            b1.Property<Guid>("MatchId")
                                .HasColumnType("uuid");

                            b1.Property<int>("PeriodNumber")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("MatchId");

                            b1.ToTable("FloorballPeriodScore");

                            b1.WithOwner()
                                .HasForeignKey("MatchId");
                        });

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("PeriodScores");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballPlayer", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Floorball.Position", "Position", b1 =>
                        {
                            b1.Property<Guid>("FloorballPlayerId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("CanPlayAsGoalkeeper")
                                .HasColumnType("boolean");

                            b1.Property<string>("PrimaryPosition")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("SecondaryPosition")
                                .HasColumnType("text");

                            b1.HasKey("FloorballPlayerId");

                            b1.ToTable("FloorballPlayers");

                            b1.WithOwner()
                                .HasForeignKey("FloorballPlayerId");
                        });

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballTeam", b =>
                {
                    b.OwnsMany("Domain.ValueObjects.Floorball.FloorballTeamPlayer", "Roster", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<int>("Assists")
                                .HasColumnType("integer");

                            b1.Property<int>("GamesPlayed")
                                .HasColumnType("integer");

                            b1.Property<int>("Goals")
                                .HasColumnType("integer");

                            b1.Property<bool>("IsActive")
                                .HasColumnType("boolean");

                            b1.Property<int?>("JerseyNumber")
                                .HasColumnType("integer");

                            b1.Property<int>("PenaltyMinutes")
                                .HasColumnType("integer");

                            b1.Property<Guid>("PlayerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Position")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid>("TeamId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("TeamId");

                            b1.ToTable("FloorballTeamPlayer");

                            b1.WithOwner()
                                .HasForeignKey("TeamId");
                        });

                    b.Navigation("Roster");
                });

            modelBuilder.Entity("FloorballMatchOfficial", b =>
                {
                    b.HasOne("Domain.Entities.Floorball.FloorballMatch", null)
                        .WithMany()
                        .HasForeignKey("MatchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Floorball.FloorballReferee", null)
                        .WithMany()
                        .HasForeignKey("OfficialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FloorballSeasonTeam", b =>
                {
                    b.HasOne("Domain.Entities.Floorball.FloorballSeason", null)
                        .WithMany()
                        .HasForeignKey("SeasonsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Floorball.FloorballTeam", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballSeason", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
