// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyLeague.Infrastructure.Persistence.Contexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyLeague.Infrastructure.Migrations.FloorBallDb
{
    [DbContext(typeof(FloorballDbContext))]
    [Migration("20250624204245_TeamPlayerIndependent")]
    partial class TeamPlayerIndependent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("floorball")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Floorball.EventSourcedFloorballMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("OfficialIdsJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<bool>("WentToOvertime")
                        .HasColumnType("boolean");

                    b.Property<bool>("WentToShootout")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("SeasonId");

                    b.ToTable("EventSourcedFloorballMatches", "floorball");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ScheduledDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Venue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("WentToOvertime")
                        .HasColumnType("boolean");

                    b.Property<bool>("WentToShootout")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("SeasonId");

                    b.ToTable("FloorballMatches", "floorball");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballMatchEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssistingPlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("DurationInMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<int?>("GoalType")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsOvertime")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsShootout")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PenaltyType")
                        .HasColumnType("integer");

                    b.Property<int>("PeriodNumber")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ScoringPlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("TimeInSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssistingPlayerId")
                        .HasDatabaseName("IX_FloorballMatchEvent_AssistingPlayerId")
                        .HasFilter("\"AssistingPlayerId\" IS NOT NULL");

                    b.HasIndex("DurationInMinutes")
                        .HasDatabaseName("IX_FloorballMatchEvent_DurationInMinutes")
                        .HasFilter("\"DurationInMinutes\" IS NOT NULL");

                    b.HasIndex("GoalType")
                        .HasDatabaseName("IX_FloorballMatchEvent_GoalType")
                        .HasFilter("\"GoalType\" IS NOT NULL");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("IX_FloorballMatchEvent_MatchId");

                    b.HasIndex("PenaltyType")
                        .HasDatabaseName("IX_FloorballMatchEvent_PenaltyType")
                        .HasFilter("\"PenaltyType\" IS NOT NULL");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_FloorballMatchEvent_PlayerId")
                        .HasFilter("\"PlayerId\" IS NOT NULL");

                    b.HasIndex("ScoringPlayerId")
                        .HasDatabaseName("IX_FloorballMatchEvent_ScoringPlayerId")
                        .HasFilter("\"ScoringPlayerId\" IS NOT NULL");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("IX_FloorballMatchEvent_TeamId");

                    b.HasIndex("MatchId", "PeriodNumber", "TimeInSeconds")
                        .HasDatabaseName("IX_FloorballMatchEvent_MatchId_Period_Time");

                    b.ToTable("FloorballMatchEvents", "floorball", t =>
                        {
                            t.HasCheckConstraint("CK_FloorballMatchEvent_PeriodNumber", "\"PeriodNumber\" > 0");

                            t.HasCheckConstraint("CK_FloorballMatchEvent_TimeInSeconds", "\"TimeInSeconds\" >= 0");

                            t.HasCheckConstraint("CK_FloorballPenalty_DurationInMinutes", "\"DurationInMinutes\" IS NULL OR \"DurationInMinutes\" > 0");
                        });

                    b.HasDiscriminator<string>("EventType").HasValue("FloorballMatchEvent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballPeriodScore", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the entity");

                    b.Property<int>("AwayScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Away team score for this period");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid")
                        .HasComment("ID of the away team");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was created");

                    b.Property<int>("HomeScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Home team score for this period");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid")
                        .HasComment("ID of the home team");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Whether the period is completed");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasComment("ID of the match this period score belongs to");

                    b.Property<int>("PeriodNumber")
                        .HasColumnType("integer")
                        .HasComment("The period number (1, 2, 3, etc.)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was last updated");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_FloorballPeriodScore_CreatedAt");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("IX_FloorballPeriodScore_MatchId");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_FloorballPeriodScore_UpdatedAt")
                        .HasFilter("\"UpdatedAt\" IS NOT NULL");

                    b.HasIndex("CreatedAt", "UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_FloorballPeriodScore_Audit");

                    b.HasIndex("MatchId", "PeriodNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_FloorballPeriodScore_Match_Period");

                    b.ToTable("FloorballPeriodScores", "floorball");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CareerAssists")
                        .HasColumnType("integer");

                    b.Property<int>("CareerGoals")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FloorballPlayers", "floorball");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballReferee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LicenseExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LicenseIssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MatchesOfficiated")
                        .HasColumnType("integer");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FloorballReferees", "floorball");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballSeason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DivisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FloorballSeasons", "floorball");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DivisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("HomeArena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrimaryJerseyColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SecondaryJerseyColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TeamCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FloorballTeams", "floorball");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballTeamManager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_FloorballTeamManager_IsActive");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("IX_FloorballTeamManager_PersonId");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("IX_FloorballTeamManager_TeamId");

                    b.ToTable("FloorballTeamManagers", "floorball");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballTeamPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the entity");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was created");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("Goals")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("JerseyNumber")
                        .HasColumnType("integer");

                    b.Property<int>("PenaltyMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was last updated");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_FloorballTeamPlayer_CreatedAt");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_FloorballTeamPlayer_PlayerId");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_FloorballTeamPlayer_UpdatedAt")
                        .HasFilter("\"UpdatedAt\" IS NOT NULL");

                    b.HasIndex("CreatedAt", "UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_FloorballTeamPlayer_Audit");

                    b.HasIndex("TeamId", "JerseyNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_FloorballTeamPlayer_TeamId_JerseyNumber")
                        .HasFilter("\"JerseyNumber\" IS NOT NULL");

                    b.HasIndex("TeamId", "PlayerId")
                        .IsUnique()
                        .HasDatabaseName("IX_FloorballTeamPlayer_TeamId_PlayerId");

                    b.ToTable("FloorballTeamPlayers", "floorball");
                });

            modelBuilder.Entity("FloorballMatchOfficial", b =>
                {
                    b.Property<Guid>("MatchesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OfficialsId")
                        .HasColumnType("uuid");

                    b.HasKey("MatchesId", "OfficialsId");

                    b.HasIndex("OfficialsId");

                    b.ToTable("FloorballMatchOfficial", "floorball");
                });

            modelBuilder.Entity("FloorballSeasonTeam", b =>
                {
                    b.Property<Guid>("SeasonsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamsId")
                        .HasColumnType("uuid");

                    b.HasKey("SeasonsId", "TeamsId");

                    b.HasIndex("TeamsId");

                    b.ToTable("FloorballSeasonTeam", "floorball");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballGoal", b =>
                {
                    b.HasBaseType("Domain.Entities.Floorball.FloorballMatchEvent");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_FloorballMatchEvent_PeriodNumber", "\"PeriodNumber\" > 0");

                            t.HasCheckConstraint("CK_FloorballMatchEvent_TimeInSeconds", "\"TimeInSeconds\" >= 0");

                            t.HasCheckConstraint("CK_FloorballPenalty_DurationInMinutes", "\"DurationInMinutes\" IS NULL OR \"DurationInMinutes\" > 0");
                        });

                    b.HasDiscriminator().HasValue("Goal");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballPenalty", b =>
                {
                    b.HasBaseType("Domain.Entities.Floorball.FloorballMatchEvent");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_FloorballMatchEvent_PeriodNumber", "\"PeriodNumber\" > 0");

                            t.HasCheckConstraint("CK_FloorballMatchEvent_TimeInSeconds", "\"TimeInSeconds\" >= 0");

                            t.HasCheckConstraint("CK_FloorballPenalty_DurationInMinutes", "\"DurationInMinutes\" IS NULL OR \"DurationInMinutes\" > 0");
                        });

                    b.HasDiscriminator().HasValue("Penalty");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.EventSourcedFloorballMatch", b =>
                {
                    b.HasOne("Domain.Entities.Floorball.FloorballTeam", null)
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Floorball.FloorballTeam", null)
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Floorball.FloorballSeason", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballMatch", b =>
                {
                    b.HasOne("Domain.Entities.Floorball.FloorballTeam", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Floorball.FloorballTeam", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Floorball.FloorballSeason", "Season")
                        .WithMany("Matches")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballMatchEvent", b =>
                {
                    b.HasOne("Domain.Entities.Floorball.FloorballPlayer", null)
                        .WithMany()
                        .HasForeignKey("AssistingPlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.Floorball.FloorballMatch", null)
                        .WithMany()
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Floorball.FloorballPlayer", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.Floorball.FloorballPlayer", null)
                        .WithMany()
                        .HasForeignKey("ScoringPlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.Floorball.FloorballTeam", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballPeriodScore", b =>
                {
                    b.HasOne("Domain.Entities.Floorball.FloorballMatch", null)
                        .WithMany("PeriodScores")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballPlayer", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Floorball.Position", "Position", b1 =>
                        {
                            b1.Property<Guid>("FloorballPlayerId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("CanPlayAsGoalkeeper")
                                .HasColumnType("boolean");

                            b1.Property<string>("PrimaryPosition")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("SecondaryPosition")
                                .HasColumnType("text");

                            b1.HasKey("FloorballPlayerId");

                            b1.ToTable("FloorballPlayers", "floorball");

                            b1.WithOwner()
                                .HasForeignKey("FloorballPlayerId");
                        });

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballTeamManager", b =>
                {
                    b.HasOne("Domain.Entities.Floorball.FloorballTeam", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballTeamPlayer", b =>
                {
                    b.HasOne("Domain.Entities.Floorball.FloorballPlayer", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Floorball.FloorballTeam", null)
                        .WithMany("Roster")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FloorballMatchOfficial", b =>
                {
                    b.HasOne("Domain.Entities.Floorball.FloorballMatch", null)
                        .WithMany()
                        .HasForeignKey("MatchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Floorball.FloorballReferee", null)
                        .WithMany()
                        .HasForeignKey("OfficialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FloorballSeasonTeam", b =>
                {
                    b.HasOne("Domain.Entities.Floorball.FloorballSeason", null)
                        .WithMany()
                        .HasForeignKey("SeasonsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Floorball.FloorballTeam", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballMatch", b =>
                {
                    b.Navigation("PeriodScores");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballSeason", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballTeam", b =>
                {
                    b.Navigation("Roster");
                });
#pragma warning restore 612, 618
        }
    }
}
