// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyLeague.Infrastructure.Persistence.Contexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyLeague.Infrastructure.Migrations.FloorBallDb
{
    [DbContext(typeof(FloorballDbContext))]
    [Migration("20251013080819_AddedSeasonDivison")]
    partial class AddedSeasonDivison
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("floorball")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Floorball.EventSourcedFloorballMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("OfficialIdsJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("ScheduledDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Venue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<bool>("WentToOvertime")
                        .HasColumnType("boolean");

                    b.Property<bool>("WentToShootout")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("SeasonId");

                    b.ToTable("EventSourcedFloorballMatches", "floorball");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballGoalieSeasonStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was created");

                    b.Property<int>("GamesPlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Number of games played");

                    b.Property<int>("GamesStarted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Number of games started");

                    b.Property<int>("GoalsAgainst")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Goals allowed");

                    b.Property<decimal>("GoalsAgainstAverage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(4,2)")
                        .HasDefaultValue(0m)
                        .HasComment("Goals against average");

                    b.Property<int>("Losses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Number of losses");

                    b.Property<int>("MinutesPlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Total minutes played");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasComment("ID of the goalie these statistics belong to");

                    b.Property<decimal>("PowerPlaySavePercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasComment("Power play save percentage");

                    b.Property<int>("PowerPlaySaves")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Power play saves");

                    b.Property<int>("PowerPlayShotsAgainst")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Power play shots faced");

                    b.Property<decimal>("SavePercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasComment("Save percentage");

                    b.Property<int>("Saves")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Total saves made");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasComment("ID of the season these statistics are for");

                    b.Property<decimal>("ShortHandedSavePercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasComment("Short-handed save percentage");

                    b.Property<int>("ShortHandedSaves")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Short-handed saves");

                    b.Property<int>("ShortHandedShotsAgainst")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Short-handed shots faced");

                    b.Property<int>("ShotsAgainst")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Total shots faced");

                    b.Property<int>("Shutouts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Number of shutouts");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasComment("ID of the team the goalie played for");

                    b.Property<int>("Ties")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Number of ties");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was last updated");

                    b.Property<int>("Wins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Number of wins");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_FloorballGoalieSeasonStatistics_PlayerId");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("IX_FloorballGoalieSeasonStatistics_SeasonId");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("IX_FloorballGoalieSeasonStatistics_TeamId");

                    b.HasIndex("SeasonId", "GoalsAgainstAverage")
                        .HasDatabaseName("IX_FloorballGoalieSeasonStatistics_SeasonId_GAA");

                    b.HasIndex("SeasonId", "SavePercentage")
                        .HasDatabaseName("IX_FloorballGoalieSeasonStatistics_SeasonId_SavePercentage");

                    b.HasIndex("SeasonId", "Wins")
                        .HasDatabaseName("IX_FloorballGoalieSeasonStatistics_SeasonId_Wins");

                    b.HasIndex("PlayerId", "TeamId", "SeasonId")
                        .IsUnique()
                        .HasDatabaseName("IX_FloorballGoalieSeasonStatistics_PlayerId_TeamId_SeasonId");

                    b.ToTable("FloorballGoalieSeasonStatistics", "floorball");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AwayActiveGoalieId")
                        .HasColumnType("uuid");

                    b.Property<int>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HomeActiveGoalieId")
                        .HasColumnType("uuid");

                    b.Property<int>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ScheduledDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Venue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("WentToOvertime")
                        .HasColumnType("boolean");

                    b.Property<bool>("WentToShootout")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("SeasonId");

                    b.ToTable("FloorballMatches", "floorball");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballMatchEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("PeriodNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("TimeInSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("IX_FloorballMatchEvent_MatchId");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("IX_FloorballMatchEvent_TeamId");

                    b.HasIndex("MatchId", "PeriodNumber", "TimeInSeconds")
                        .HasDatabaseName("IX_FloorballMatchEvent_MatchId_Period_Time");

                    b.ToTable("FloorballMatchEvents", "floorball", t =>
                        {
                            t.HasCheckConstraint("CK_FloorballMatchEvent_PeriodNumber", "\"PeriodNumber\" > 0");

                            t.HasCheckConstraint("CK_FloorballMatchEvent_TimeInSeconds", "\"TimeInSeconds\" >= 0");

                            t.HasCheckConstraint("CK_FloorballPenalty_DurationInMinutes", "\"DurationInMinutes\" IS NULL OR \"DurationInMinutes\" > 0");
                        });

                    b.HasDiscriminator<string>("EventType").HasValue("FloorballMatchEvent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballMatchTeamStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BlockedShots")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Shots blocked");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was created");

                    b.Property<int>("FaceoffAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Total faceoffs");

                    b.Property<decimal>("FaceoffPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasComment("Faceoff win percentage");

                    b.Property<int>("FaceoffWins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Faceoffs won");

                    b.Property<int>("Giveaways")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Giveaways");

                    b.Property<int>("Hits")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Hits delivered");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasComment("ID of the match these statistics belong to");

                    b.Property<int>("PenaltyKillOpportunities")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Penalty kill opportunities");

                    b.Property<int>("PenaltyKillSuccess")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Successful penalty kills");

                    b.Property<int>("PenaltyMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Penalty minutes");

                    b.Property<int>("PowerPlayGoals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Power play goals");

                    b.Property<int>("PowerPlayMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Power play minutes");

                    b.Property<int>("PowerPlayOpportunities")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Power play opportunities");

                    b.Property<int>("ShortHandedGoals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Short-handed goals");

                    b.Property<decimal>("ShotPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasComment("Shot percentage");

                    b.Property<int>("ShotsOnGoal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Shots on goal");

                    b.Property<int>("ShotsTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Total shots taken");

                    b.Property<int>("Takeaways")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Takeaways");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasComment("ID of the team these statistics are for");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was last updated");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("IX_FloorballMatchTeamStatistics_MatchId");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("IX_FloorballMatchTeamStatistics_TeamId");

                    b.HasIndex("MatchId", "TeamId")
                        .IsUnique()
                        .HasDatabaseName("IX_FloorballMatchTeamStatistics_MatchId_TeamId");

                    b.ToTable("FloorballMatchTeamStatistics", "floorball");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballPeriodScore", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the entity");

                    b.Property<int>("AwayScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Away team score for this period");

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid")
                        .HasComment("ID of the away team");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was created");

                    b.Property<int>("HomeScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Home team score for this period");

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid")
                        .HasComment("ID of the home team");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Whether the period is completed");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid")
                        .HasComment("ID of the match this period score belongs to");

                    b.Property<int>("PeriodNumber")
                        .HasColumnType("integer")
                        .HasComment("The period number (1, 2, 3, etc.)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was last updated");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_FloorballPeriodScore_CreatedAt");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("IX_FloorballPeriodScore_MatchId");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_FloorballPeriodScore_UpdatedAt")
                        .HasFilter("\"UpdatedAt\" IS NOT NULL");

                    b.HasIndex("CreatedAt", "UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_FloorballPeriodScore_Audit");

                    b.HasIndex("MatchId", "PeriodNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_FloorballPeriodScore_Match_Period");

                    b.ToTable("FloorballPeriodScores", "floorball");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CareerAssists")
                        .HasColumnType("integer");

                    b.Property<int>("CareerGoals")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FloorballPlayers", "floorball");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballPlayerSeasonStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Assists")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Assists made");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was created");

                    b.Property<int>("FaceoffAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Total faceoffs taken");

                    b.Property<decimal>("FaceoffPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasComment("Faceoff win percentage");

                    b.Property<int>("FaceoffWins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Faceoffs won");

                    b.Property<int>("GameWinningGoals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Game-winning goals");

                    b.Property<int>("GamesPlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Number of games played");

                    b.Property<int>("Goals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Goals scored");

                    b.Property<int>("OvertimeGoals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Overtime goals");

                    b.Property<int>("PenaltyMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Penalty minutes");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasComment("ID of the player these statistics belong to");

                    b.Property<int>("PlusMinusRating")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Plus/minus rating");

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Total points (goals + assists)");

                    b.Property<int>("PowerPlayAssists")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Power play assists");

                    b.Property<int>("PowerPlayGoals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Power play goals");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasComment("ID of the season these statistics are for");

                    b.Property<int>("ShortHandedAssists")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Short-handed assists");

                    b.Property<int>("ShortHandedGoals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Short-handed goals");

                    b.Property<decimal>("ShotPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasComment("Shooting percentage");

                    b.Property<int>("ShotsOnGoal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Shots on goal");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasComment("ID of the team the player played for");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was last updated");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_FloorballPlayerSeasonStatistics_PlayerId");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("IX_FloorballPlayerSeasonStatistics_SeasonId");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("IX_FloorballPlayerSeasonStatistics_TeamId");

                    b.HasIndex("SeasonId", "Assists")
                        .HasDatabaseName("IX_FloorballPlayerSeasonStatistics_SeasonId_Assists");

                    b.HasIndex("SeasonId", "Goals")
                        .HasDatabaseName("IX_FloorballPlayerSeasonStatistics_SeasonId_Goals");

                    b.HasIndex("SeasonId", "Points")
                        .HasDatabaseName("IX_FloorballPlayerSeasonStatistics_SeasonId_Points");

                    b.HasIndex("PlayerId", "TeamId", "SeasonId")
                        .IsUnique()
                        .HasDatabaseName("IX_FloorballPlayerSeasonStatistics_PlayerId_TeamId_SeasonId");

                    b.ToTable("FloorballPlayerSeasonStatistics", "floorball");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballReferee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LicenseExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LicenseIssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MatchesOfficiated")
                        .HasColumnType("integer");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FloorballReferees", "floorball");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballSeason", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DivisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FloorballSeasons", "floorball");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballSeasonDivision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DivisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId", "DivisionId")
                        .IsUnique()
                        .HasDatabaseName("IX_FloorballSeasonDivisions_Season_Division");

                    b.ToTable("FloorballSeasonDivisions", "floorball");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballSeasonDivisionTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SeasonDivisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("SeasonDivisionId", "TeamId")
                        .IsUnique()
                        .HasDatabaseName("IX_FloorballSeasonDivisionTeams_SeasonDivision_Team");

                    b.HasIndex("SeasonId", "TeamId")
                        .IsUnique()
                        .HasDatabaseName("IX_FloorballSeasonDivisionTeams_Season_Team");

                    b.ToTable("FloorballSeasonDivisionTeams", "floorball");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballStatisticsCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CacheKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Unique cache key identifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was created");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("When this cache entry expires");

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasComment("Serialized JSON data");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("When this cache entry was last updated");

                    b.Property<Guid?>("SeasonId")
                        .HasColumnType("uuid")
                        .HasComment("Optional season ID this cache is associated with");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was last updated");

                    b.HasKey("Id");

                    b.HasIndex("CacheKey")
                        .IsUnique()
                        .HasDatabaseName("IX_FloorballStatisticsCache_CacheKey");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("IX_FloorballStatisticsCache_ExpiresAt");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("IX_FloorballStatisticsCache_SeasonId");

                    b.HasIndex("SeasonId", "ExpiresAt")
                        .HasDatabaseName("IX_FloorballStatisticsCache_SeasonId_ExpiresAt");

                    b.ToTable("FloorballStatisticsCache", "floorball");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DivisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("HomeArena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrimaryJerseyColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SecondaryJerseyColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TeamCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FloorballTeams", "floorball");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballTeamManager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("IX_FloorballTeamManager_IsActive");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("IX_FloorballTeamManager_PersonId");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("IX_FloorballTeamManager_TeamId");

                    b.ToTable("FloorballTeamManagers", "floorball");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballTeamPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the entity");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was created");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("Goals")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("JerseyNumber")
                        .HasColumnType("integer");

                    b.Property<int>("PenaltyMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was last updated");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_FloorballTeamPlayer_CreatedAt");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_FloorballTeamPlayer_PlayerId");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_FloorballTeamPlayer_UpdatedAt")
                        .HasFilter("\"UpdatedAt\" IS NOT NULL");

                    b.HasIndex("CreatedAt", "UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_FloorballTeamPlayer_Audit");

                    b.HasIndex("TeamId", "JerseyNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_FloorballTeamPlayer_TeamId_JerseyNumber")
                        .HasFilter("\"JerseyNumber\" IS NOT NULL");

                    b.HasIndex("TeamId", "PlayerId")
                        .IsUnique()
                        .HasDatabaseName("IX_FloorballTeamPlayer_TeamId_PlayerId");

                    b.ToTable("FloorballTeamPlayers", "floorball");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballTeamSeasonStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AwayLosses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Away losses");

                    b.Property<int>("AwayWins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Away wins");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was created");

                    b.Property<int>("FaceoffAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Total faceoffs taken");

                    b.Property<decimal>("FaceoffPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasComment("Faceoff win percentage");

                    b.Property<int>("FaceoffWins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Faceoffs won");

                    b.Property<int>("GamesPlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Number of games played");

                    b.Property<int>("GoalDifference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Goal difference (goals for - goals against)");

                    b.Property<int>("GoalsAgainst")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Total goals conceded");

                    b.Property<int>("GoalsFor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Total goals scored");

                    b.Property<int>("HomeLosses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Home losses");

                    b.Property<int>("HomeWins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Home wins");

                    b.Property<int>("Losses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Number of losses");

                    b.Property<int>("PenaltyKillOpportunities")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Penalty kill opportunities");

                    b.Property<decimal>("PenaltyKillPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasComment("Penalty kill success percentage");

                    b.Property<int>("PenaltyMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Total penalty minutes");

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Total points earned");

                    b.Property<int>("PowerPlayGoals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Power play goals scored");

                    b.Property<int>("PowerPlayOpportunities")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Power play opportunities");

                    b.Property<decimal>("PowerPlayPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasComment("Power play success percentage");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uuid")
                        .HasComment("ID of the season these statistics are for");

                    b.Property<int>("ShortHandedGoals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Short-handed goals scored");

                    b.Property<decimal>("ShotPercentage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0m)
                        .HasComment("Shot percentage");

                    b.Property<int>("ShotsAgainst")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Total shots faced");

                    b.Property<int>("ShotsFor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Total shots taken");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasComment("ID of the team these statistics belong to");

                    b.Property<int>("Ties")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Number of ties/overtime losses");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was last updated");

                    b.Property<int>("Wins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasComment("Number of wins");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId")
                        .HasDatabaseName("IX_FloorballTeamSeasonStatistics_SeasonId");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("IX_FloorballTeamSeasonStatistics_TeamId");

                    b.HasIndex("TeamId", "SeasonId")
                        .IsUnique()
                        .HasDatabaseName("IX_FloorballTeamSeasonStatistics_TeamId_SeasonId");

                    b.ToTable("FloorballTeamSeasonStatistics", "floorball");
                });

            modelBuilder.Entity("FloorballMatchOfficial", b =>
                {
                    b.Property<Guid>("MatchesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OfficialsId")
                        .HasColumnType("uuid");

                    b.HasKey("MatchesId", "OfficialsId");

                    b.HasIndex("OfficialsId");

                    b.ToTable("FloorballMatchOfficial", "floorball");
                });

            modelBuilder.Entity("FloorballSeasonTeam", b =>
                {
                    b.Property<Guid>("SeasonsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamsId")
                        .HasColumnType("uuid");

                    b.HasKey("SeasonsId", "TeamsId");

                    b.HasIndex("TeamsId");

                    b.ToTable("FloorballSeasonTeam", "floorball");
                });

            modelBuilder.Entity("MyLeague.Infrastructure.Persistence.EventStores.FloorballStoredEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("uuid");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AggregateId", "Version")
                        .IsUnique();

                    b.ToTable("FloorballEventStore", "floorball");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballGoal", b =>
                {
                    b.HasBaseType("Domain.Entities.Floorball.FloorballMatchEvent");

                    b.Property<Guid?>("AssistingPlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FloorballMatchId")
                        .HasColumnType("uuid");

                    b.Property<int?>("GoalType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ScoringPlayerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SecondaryAssistingPlayerId")
                        .HasColumnType("uuid");

                    b.HasIndex("AssistingPlayerId")
                        .HasDatabaseName("IX_FloorballMatchEvent_AssistingPlayerId");

                    b.HasIndex("FloorballMatchId");

                    b.HasIndex("GoalType")
                        .HasDatabaseName("IX_FloorballMatchEvent_GoalType");

                    b.HasIndex("ScoringPlayerId")
                        .HasDatabaseName("IX_FloorballMatchEvent_ScoringPlayerId");

                    b.HasIndex("SecondaryAssistingPlayerId")
                        .HasDatabaseName("IX_FloorballMatchEvent_SecondaryAssistingPlayerId");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_FloorballMatchEvent_PeriodNumber", "\"PeriodNumber\" > 0");

                            t.HasCheckConstraint("CK_FloorballMatchEvent_TimeInSeconds", "\"TimeInSeconds\" >= 0");

                            t.HasCheckConstraint("CK_FloorballPenalty_DurationInMinutes", "\"DurationInMinutes\" IS NULL OR \"DurationInMinutes\" > 0");
                        });

                    b.HasDiscriminator().HasValue("Goal");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballPenalty", b =>
                {
                    b.HasBaseType("Domain.Entities.Floorball.FloorballMatchEvent");

                    b.Property<int>("DurationInMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FloorballMatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("PenaltyType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasIndex("DurationInMinutes")
                        .HasDatabaseName("IX_FloorballMatchEvent_DurationInMinutes");

                    b.HasIndex("FloorballMatchId");

                    b.HasIndex("PenaltyType")
                        .HasDatabaseName("IX_FloorballMatchEvent_PenaltyType");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_FloorballMatchEvent_PlayerId");

                    b.ToTable("FloorballMatchEvents", "floorball", t =>
                        {
                            t.HasCheckConstraint("CK_FloorballMatchEvent_PeriodNumber", "\"PeriodNumber\" > 0");

                            t.HasCheckConstraint("CK_FloorballMatchEvent_TimeInSeconds", "\"TimeInSeconds\" >= 0");

                            t.HasCheckConstraint("CK_FloorballPenalty_DurationInMinutes", "\"DurationInMinutes\" IS NULL OR \"DurationInMinutes\" > 0");

                            t.Property("FloorballMatchId")
                                .HasColumnName("FloorballPenalty_FloorballMatchId");
                        });

                    b.HasDiscriminator().HasValue("Penalty");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballSave", b =>
                {
                    b.HasBaseType("Domain.Entities.Floorball.FloorballMatchEvent");

                    b.Property<Guid?>("FloorballMatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GoalieId")
                        .HasColumnType("uuid");

                    b.Property<bool>("WasInOvertime")
                        .HasColumnType("boolean");

                    b.Property<bool>("WasInShootout")
                        .HasColumnType("boolean");

                    b.HasIndex("FloorballMatchId");

                    b.HasIndex("GoalieId")
                        .HasDatabaseName("IX_FloorballMatchEvent_GoalieId");

                    b.ToTable("FloorballMatchEvents", "floorball", t =>
                        {
                            t.HasCheckConstraint("CK_FloorballMatchEvent_PeriodNumber", "\"PeriodNumber\" > 0");

                            t.HasCheckConstraint("CK_FloorballMatchEvent_TimeInSeconds", "\"TimeInSeconds\" >= 0");

                            t.HasCheckConstraint("CK_FloorballPenalty_DurationInMinutes", "\"DurationInMinutes\" IS NULL OR \"DurationInMinutes\" > 0");

                            t.Property("FloorballMatchId")
                                .HasColumnName("FloorballSave_FloorballMatchId");
                        });

                    b.HasDiscriminator().HasValue("Save");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.EventSourcedFloorballMatch", b =>
                {
                    b.HasOne("Domain.Entities.Floorball.FloorballTeam", null)
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Floorball.FloorballTeam", null)
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Floorball.FloorballSeason", null)
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballMatch", b =>
                {
                    b.HasOne("Domain.Entities.Floorball.FloorballTeam", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Floorball.FloorballTeam", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Floorball.FloorballSeason", "Season")
                        .WithMany("Matches")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballMatchEvent", b =>
                {
                    b.HasOne("Domain.Entities.Floorball.FloorballMatch", null)
                        .WithMany("Events")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Floorball.FloorballTeam", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballPeriodScore", b =>
                {
                    b.HasOne("Domain.Entities.Floorball.FloorballMatch", null)
                        .WithMany("PeriodScores")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballPlayer", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Floorball.Position", "Position", b1 =>
                        {
                            b1.Property<Guid>("FloorballPlayerId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("CanPlayAsGoalkeeper")
                                .HasColumnType("boolean");

                            b1.Property<string>("PrimaryPosition")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("SecondaryPosition")
                                .HasColumnType("text");

                            b1.HasKey("FloorballPlayerId");

                            b1.ToTable("FloorballPlayers", "floorball");

                            b1.WithOwner()
                                .HasForeignKey("FloorballPlayerId");
                        });

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballSeasonDivision", b =>
                {
                    b.HasOne("Domain.Entities.Floorball.FloorballSeason", "Season")
                        .WithMany()
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballSeasonDivisionTeam", b =>
                {
                    b.HasOne("Domain.Entities.Floorball.FloorballSeasonDivision", "SeasonDivision")
                        .WithMany("Teams")
                        .HasForeignKey("SeasonDivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Floorball.FloorballTeam", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SeasonDivision");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballTeamManager", b =>
                {
                    b.HasOne("Domain.Entities.Floorball.FloorballTeam", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballTeamPlayer", b =>
                {
                    b.HasOne("Domain.Entities.Floorball.FloorballPlayer", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Floorball.FloorballTeam", null)
                        .WithMany("Roster")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FloorballMatchOfficial", b =>
                {
                    b.HasOne("Domain.Entities.Floorball.FloorballMatch", null)
                        .WithMany()
                        .HasForeignKey("MatchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Floorball.FloorballReferee", null)
                        .WithMany()
                        .HasForeignKey("OfficialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FloorballSeasonTeam", b =>
                {
                    b.HasOne("Domain.Entities.Floorball.FloorballSeason", null)
                        .WithMany()
                        .HasForeignKey("SeasonsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Floorball.FloorballTeam", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballGoal", b =>
                {
                    b.HasOne("Domain.Entities.Floorball.FloorballMatch", null)
                        .WithMany("GoalEvents")
                        .HasForeignKey("FloorballMatchId");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballPenalty", b =>
                {
                    b.HasOne("Domain.Entities.Floorball.FloorballMatch", null)
                        .WithMany("PenaltyEvents")
                        .HasForeignKey("FloorballMatchId");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballSave", b =>
                {
                    b.HasOne("Domain.Entities.Floorball.FloorballMatch", null)
                        .WithMany("SaveEvents")
                        .HasForeignKey("FloorballMatchId");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballMatch", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("GoalEvents");

                    b.Navigation("PenaltyEvents");

                    b.Navigation("PeriodScores");

                    b.Navigation("SaveEvents");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballSeason", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballSeasonDivision", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Domain.Entities.Floorball.FloorballTeam", b =>
                {
                    b.Navigation("Roster");
                });
#pragma warning restore 612, 618
        }
    }
}
