services:
  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: src/backend/WebAPI/Dockerfile
    depends_on:
      postgres:
        condition: service_healthy
      seq:
         condition: service_started
    networks:
      - myleague-network

  postgres:
    image: postgres:16-alpine
    container_name: myleague-postgres
    environment:
      POSTGRES_DB: myleague
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - myleague-network

  seq:
    image: datalust/seq:latest
    container_name: myleague-seq
    environment:
      ACCEPT_EULA: Y
      SEQ_FIRSTRUN_NOAUTHENTICATION: "true"
    ports:
      - "5341:80"
    volumes:
      - seq_data:/data
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://localhost:80/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
    restart: unless-stopped
    networks:
      - myleague-network

  frontend:
    build:
      context: src/frontend
      dockerfile: Dockerfile
    container_name: myleague-frontend
    environment:
      - DOCKER=true
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
    ports:
      - '5173:5173'
    depends_on:
      - webapi
    networks:
      - myleague-network


volumes:
  postgres_data:
  seq_data:

networks:
  myleague-network:
    driver: bridge
