// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyLeague.Infrastructure.Persistence.Contexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyLeague.Infrastructure.Migrations.HockeyDb
{
    [DbContext(typeof(HockeyDbContext))]
    [Migration("20260708102047_InitialHockeySchema")]
    partial class InitialHockeySchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("hockey")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Hockey.Competitions.HockeyCompetition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CompetitionType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("_playoffSchedule")
                        .HasColumnType("jsonb")
                        .HasColumnName("PlayoffSchedule");

                    b.HasKey("Id");

                    b.ToTable("HockeyCompetitions", "hockey");

                    b.HasDiscriminator<int>("CompetitionType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Competitions.HockeyCompetitionDivision", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the entity");

                    b.Property<Guid?>("ChampionCompetitionTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was created");

                    b.Property<Guid>("DivisionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was last updated");

                    b.HasKey("Id");

                    b.HasIndex("ChampionCompetitionTeamId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_HockeyCompetitionDivision_CreatedAt");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_HockeyCompetitionDivision_UpdatedAt")
                        .HasFilter("\"UpdatedAt\" IS NOT NULL");

                    b.HasIndex("CompetitionId", "DivisionId")
                        .IsUnique()
                        .HasDatabaseName("IX_HockeyCompetitionDivisions_Competition_Division");

                    b.HasIndex("CreatedAt", "UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_HockeyCompetitionDivision_Audit");

                    b.ToTable("HockeyCompetitionDivisions", "hockey");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Competitions.HockeyCompetitionDivisionTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the entity");

                    b.Property<Guid>("CompetitionDivisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionTeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was created");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("Seed")
                        .HasColumnType("integer");

                    b.Property<int?>("StandingRank")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was last updated");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionTeamId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_HockeyCompetitionDivisionTeam_CreatedAt");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_HockeyCompetitionDivisionTeam_UpdatedAt")
                        .HasFilter("\"UpdatedAt\" IS NOT NULL");

                    b.HasIndex("CompetitionDivisionId", "CompetitionTeamId")
                        .IsUnique()
                        .HasDatabaseName("IX_HockeyCompetitionDivisionTeams_Division_CompetitionTeam_Active")
                        .HasFilter("\"IsActive\" = true");

                    b.HasIndex("CreatedAt", "UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_HockeyCompetitionDivisionTeam_Audit");

                    b.ToTable("HockeyCompetitionDivisionTeams", "hockey");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Competitions.HockeyCompetitionTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the entity");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was created");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Seed")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was last updated");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_HockeyCompetitionTeam_CreatedAt");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_HockeyCompetitionTeam_UpdatedAt")
                        .HasFilter("\"UpdatedAt\" IS NOT NULL");

                    b.HasIndex("CompetitionId", "TeamId")
                        .IsUnique()
                        .HasDatabaseName("IX_HockeyCompetitionTeams_Competition_Team_Active")
                        .HasFilter("\"LeftAt\" IS NULL");

                    b.HasIndex("CreatedAt", "UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_HockeyCompetitionTeam_Audit");

                    b.ToTable("HockeyCompetitionTeams", "hockey");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Competitions.HockeyPlayoffSeries", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the entity");

                    b.Property<Guid?>("AwayCompetitionTeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("AwayTeamWins")
                        .HasColumnType("integer");

                    b.Property<int>("BestOf")
                        .HasColumnType("integer");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was created");

                    b.Property<Guid?>("HomeCompetitionTeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("HomeTeamWins")
                        .HasColumnType("integer");

                    b.Property<string>("Round")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeriesOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was last updated");

                    b.Property<Guid?>("WinnerCompetitionTeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("AwayCompetitionTeamId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_HockeyPlayoffSeries_CreatedAt");

                    b.HasIndex("HomeCompetitionTeamId");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_HockeyPlayoffSeries_UpdatedAt")
                        .HasFilter("\"UpdatedAt\" IS NOT NULL");

                    b.HasIndex("WinnerCompetitionTeamId");

                    b.HasIndex("CreatedAt", "UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_HockeyPlayoffSeries_Audit");

                    b.HasIndex("CompetitionId", "Round", "SeriesOrder")
                        .IsUnique()
                        .HasDatabaseName("IX_HockeyPlayoffSeries_Competition_Round_Order");

                    b.ToTable("HockeyPlayoffSeries", "hockey");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Competitions.HockeyTournamentGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the entity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was created");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was last updated");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_HockeyTournamentGroup_CreatedAt");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_HockeyTournamentGroup_UpdatedAt")
                        .HasFilter("\"UpdatedAt\" IS NOT NULL");

                    b.HasIndex("CreatedAt", "UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_HockeyTournamentGroup_Audit");

                    b.HasIndex("TournamentId", "SortOrder")
                        .HasDatabaseName("IX_HockeyTournamentGroups_Tournament_SortOrder");

                    b.ToTable("HockeyTournamentGroups", "hockey");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Competitions.HockeyTournamentGroupTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the entity");

                    b.Property<Guid>("CompetitionTeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was created");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("Seed")
                        .HasColumnType("integer");

                    b.Property<Guid>("TournamentGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was last updated");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionTeamId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_HockeyTournamentGroupTeam_CreatedAt");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_HockeyTournamentGroupTeam_UpdatedAt")
                        .HasFilter("\"UpdatedAt\" IS NOT NULL");

                    b.HasIndex("CreatedAt", "UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_HockeyTournamentGroupTeam_Audit");

                    b.HasIndex("TournamentGroupId", "CompetitionTeamId")
                        .IsUnique()
                        .HasDatabaseName("IX_HockeyTournamentGroupTeams_Group_CompetitionTeam_Active")
                        .HasFilter("\"IsActive\" = true");

                    b.ToTable("HockeyTournamentGroupTeams", "hockey");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Matches.HockeyMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the entity");

                    b.Property<Guid?>("AwayCompetitionTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was created");

                    b.Property<Guid?>("HomeCompetitionTeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was last updated");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_HockeyMatch_CreatedAt");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_HockeyMatch_UpdatedAt")
                        .HasFilter("\"UpdatedAt\" IS NOT NULL");

                    b.HasIndex("CreatedAt", "UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_HockeyMatch_Audit");

                    b.ToTable("HockeyMatches", "hockey");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Teams.HockeyLine", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the entity");

                    b.Property<Guid?>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was created");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("LineNumber")
                        .HasColumnType("integer");

                    b.Property<string>("LineType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was last updated");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_HockeyLine_CreatedAt");

                    b.HasIndex("TeamId");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_HockeyLine_UpdatedAt")
                        .HasFilter("\"UpdatedAt\" IS NOT NULL");

                    b.HasIndex("CreatedAt", "UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_HockeyLine_Audit");

                    b.ToTable("HockeyLines", "hockey");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Teams.HockeyLinePlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the entity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was created");

                    b.Property<Guid>("LineId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TeamPlayerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was last updated");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_HockeyLinePlayer_CreatedAt");

                    b.HasIndex("TeamPlayerId");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_HockeyLinePlayer_UpdatedAt")
                        .HasFilter("\"UpdatedAt\" IS NOT NULL");

                    b.HasIndex("CreatedAt", "UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_HockeyLinePlayer_Audit");

                    b.HasIndex("LineId", "TeamPlayerId")
                        .IsUnique()
                        .HasDatabaseName("IX_HockeyLinePlayers_Line_TeamPlayer");

                    b.ToTable("HockeyLinePlayers", "hockey");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Teams.HockeyOfficial", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the entity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was created");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LicenseExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LicenseIssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MatchesOfficiated")
                        .HasColumnType("integer");

                    b.Property<string>("OfficialNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("OfficialRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was last updated");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_HockeyOfficial_CreatedAt");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("IX_HockeyOfficials_PersonId");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_HockeyOfficial_UpdatedAt")
                        .HasFilter("\"UpdatedAt\" IS NOT NULL");

                    b.HasIndex("CreatedAt", "UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_HockeyOfficial_Audit");

                    b.ToTable("HockeyOfficials", "hockey");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Teams.HockeyPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the entity");

                    b.Property<int>("CareerAssists")
                        .HasColumnType("integer");

                    b.Property<int>("CareerFaceoffAttempts")
                        .HasColumnType("integer");

                    b.Property<int>("CareerFaceoffWins")
                        .HasColumnType("integer");

                    b.Property<int>("CareerGamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("CareerGoals")
                        .HasColumnType("integer");

                    b.Property<int>("CareerPenaltyMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Catches")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was created");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrimaryPosition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Shoots")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was last updated");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_HockeyPlayer_CreatedAt");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("IX_HockeyPlayers_PersonId");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_HockeyPlayer_UpdatedAt")
                        .HasFilter("\"UpdatedAt\" IS NOT NULL");

                    b.HasIndex("CreatedAt", "UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_HockeyPlayer_Audit");

                    b.ToTable("HockeyPlayers", "hockey");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Teams.HockeyTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DivisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("HomeArena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrimaryJerseyColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SecondaryJerseyColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("TeamCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("HockeyTeams", "hockey");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Teams.HockeyTeamPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the entity");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<string>("CaptainRole")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was created");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("Goals")
                        .HasColumnType("integer");

                    b.Property<int?>("JerseyNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PenaltyMinutes")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("RequestedJerseyNumber")
                        .HasColumnType("integer");

                    b.Property<string>("RosterStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was last updated");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_HockeyTeamPlayer_CreatedAt");

                    b.HasIndex("PlayerId");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_HockeyTeamPlayer_UpdatedAt")
                        .HasFilter("\"UpdatedAt\" IS NOT NULL");

                    b.HasIndex("CreatedAt", "UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_HockeyTeamPlayer_Audit");

                    b.HasIndex("TeamId", "CompetitionId", "JerseyNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_HockeyTeamPlayers_Team_Competition_Jersey_Active")
                        .HasFilter("\"JerseyNumber\" IS NOT NULL AND \"LeftAt\" IS NULL");

                    b.HasIndex("TeamId", "PlayerId", "CompetitionId")
                        .IsUnique()
                        .HasDatabaseName("IX_HockeyTeamPlayers_Team_Player_Competition_Active")
                        .HasFilter("\"LeftAt\" IS NULL");

                    b.ToTable("HockeyTeamPlayers", "hockey");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Teams.HockeyTeamStaff", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the entity");

                    b.Property<Guid?>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was created");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LeftAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was last updated");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_HockeyTeamStaff_CreatedAt");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_HockeyTeamStaff_UpdatedAt")
                        .HasFilter("\"UpdatedAt\" IS NOT NULL");

                    b.HasIndex("CreatedAt", "UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_HockeyTeamStaff_Audit");

                    b.HasIndex("TeamId", "PersonId", "Role", "CompetitionId")
                        .IsUnique()
                        .HasDatabaseName("IX_HockeyTeamStaff_Team_Person_Role_Competition_Active")
                        .HasFilter("\"LeftAt\" IS NULL");

                    b.ToTable("HockeyTeamStaff", "hockey");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Competitions.HockeySeason", b =>
                {
                    b.HasBaseType("Domain.Entities.Hockey.Competitions.HockeyCompetition");

                    b.Property<Guid?>("ChampionCompetitionTeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("SeasonCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Competitions.HockeyTournament", b =>
                {
                    b.HasBaseType("Domain.Entities.Hockey.Competitions.HockeyCompetition");

                    b.Property<Guid?>("ChampionCompetitionTeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHtml")
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)");

                    b.Property<string>("CurrentStage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Venue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.ToTable("HockeyCompetitions", "hockey", t =>
                        {
                            t.Property("ChampionCompetitionTeamId")
                                .HasColumnName("HockeyTournament_ChampionCompetitionTeamId");
                        });

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Competitions.HockeyCompetition", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Hockey.Rules.HockeyCompetitionRules", "CompetitionRules", b1 =>
                        {
                            b1.Property<Guid>("HockeyCompetitionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("CompetitionRules_Name");

                            b1.Property<string>("RuleBookSource")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("CompetitionRules_RuleBookSource");

                            b1.Property<string>("RuleBookVersion")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("CompetitionRules_RuleBookVersion");

                            b1.HasKey("HockeyCompetitionId");

                            b1.ToTable("HockeyCompetitions", "hockey");

                            b1.WithOwner()
                                .HasForeignKey("HockeyCompetitionId");

                            b1.OwnsOne("Domain.ValueObjects.Hockey.Rules.HockeyContactRules", "ContactRules", b2 =>
                                {
                                    b2.Property<Guid>("HockeyCompetitionRulesHockeyCompetitionId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("AutomaticGameMisconductForFight")
                                        .HasColumnType("boolean")
                                        .HasColumnName("CompetitionRules_Contact_AutomaticGameMisconductForFight");

                                    b2.Property<bool>("BodyCheckingAllowed")
                                        .HasColumnType("boolean")
                                        .HasColumnName("CompetitionRules_Contact_BodyCheckingAllowed");

                                    b2.Property<bool>("FightingAllowed")
                                        .HasColumnType("boolean")
                                        .HasColumnName("CompetitionRules_Contact_FightingAllowed");

                                    b2.Property<bool>("OpenIceHitsAllowed")
                                        .HasColumnType("boolean")
                                        .HasColumnName("CompetitionRules_Contact_OpenIceHitsAllowed");

                                    b2.Property<bool>("StrictHeadContactRule")
                                        .HasColumnType("boolean")
                                        .HasColumnName("CompetitionRules_Contact_StrictHeadContactRule");

                                    b2.HasKey("HockeyCompetitionRulesHockeyCompetitionId");

                                    b2.ToTable("HockeyCompetitions", "hockey");

                                    b2.WithOwner()
                                        .HasForeignKey("HockeyCompetitionRulesHockeyCompetitionId");
                                });

                            b1.OwnsOne("Domain.ValueObjects.Hockey.Rules.HockeyMatchRules", "MatchRules", b2 =>
                                {
                                    b2.Property<Guid>("HockeyCompetitionRulesHockeyCompetitionId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("DelayedOffsideEnabled")
                                        .HasColumnType("boolean")
                                        .HasColumnName("CompetitionRules_Match_DelayedOffsideEnabled");

                                    b2.Property<bool>("GoaliePullAllowed")
                                        .HasColumnType("boolean")
                                        .HasColumnName("CompetitionRules_Match_GoaliePullAllowed");

                                    b2.Property<string>("IcingRule")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CompetitionRules_Match_IcingRule");

                                    b2.Property<bool>("OffsideEnabled")
                                        .HasColumnType("boolean")
                                        .HasColumnName("CompetitionRules_Match_OffsideEnabled");

                                    b2.Property<bool>("OvertimeEnabled")
                                        .HasColumnType("boolean")
                                        .HasColumnName("CompetitionRules_Match_OvertimeEnabled");

                                    b2.Property<int>("OvertimeLengthMinutes")
                                        .HasColumnType("integer")
                                        .HasColumnName("CompetitionRules_Match_OvertimeLengthMinutes");

                                    b2.Property<bool>("PenaltyShotEnabled")
                                        .HasColumnType("boolean")
                                        .HasColumnName("CompetitionRules_Match_PenaltyShotEnabled");

                                    b2.Property<int>("RegularPeriodCount")
                                        .HasColumnType("integer")
                                        .HasColumnName("CompetitionRules_Match_RegularPeriodCount");

                                    b2.Property<int>("RegularPeriodLengthMinutes")
                                        .HasColumnType("integer")
                                        .HasColumnName("CompetitionRules_Match_RegularPeriodLengthMinutes");

                                    b2.Property<bool>("ShootoutEnabled")
                                        .HasColumnType("boolean")
                                        .HasColumnName("CompetitionRules_Match_ShootoutEnabled");

                                    b2.Property<bool>("StopClock")
                                        .HasColumnType("boolean")
                                        .HasColumnName("CompetitionRules_Match_StopClock");

                                    b2.HasKey("HockeyCompetitionRulesHockeyCompetitionId");

                                    b2.ToTable("HockeyCompetitions", "hockey");

                                    b2.WithOwner()
                                        .HasForeignKey("HockeyCompetitionRulesHockeyCompetitionId");
                                });

                            b1.OwnsOne("Domain.ValueObjects.Hockey.Rules.HockeyRosterRules", "RosterRules", b2 =>
                                {
                                    b2.Property<Guid>("HockeyCompetitionRulesHockeyCompetitionId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("AllowGuestPlayers")
                                        .HasColumnType("boolean")
                                        .HasColumnName("CompetitionRules_Roster_AllowGuestPlayers");

                                    b2.Property<bool>("CanGoalieBeCaptain")
                                        .HasColumnType("boolean")
                                        .HasColumnName("CompetitionRules_Roster_CanGoalieBeCaptain");

                                    b2.Property<bool>("LineManagementEnabled")
                                        .HasColumnType("boolean")
                                        .HasColumnName("CompetitionRules_Roster_LineManagementEnabled");

                                    b2.Property<int>("MaxAlternateCaptains")
                                        .HasColumnType("integer")
                                        .HasColumnName("CompetitionRules_Roster_MaxAlternateCaptains");

                                    b2.Property<int>("MaxCaptains")
                                        .HasColumnType("integer")
                                        .HasColumnName("CompetitionRules_Roster_MaxCaptains");

                                    b2.Property<int>("MaxDressedGoalies")
                                        .HasColumnType("integer")
                                        .HasColumnName("CompetitionRules_Roster_MaxDressedGoalies");

                                    b2.Property<int>("MaxDressedPlayers")
                                        .HasColumnType("integer")
                                        .HasColumnName("CompetitionRules_Roster_MaxDressedPlayers");

                                    b2.Property<int>("MinDressedPlayers")
                                        .HasColumnType("integer")
                                        .HasColumnName("CompetitionRules_Roster_MinDressedPlayers");

                                    b2.Property<bool>("RequiresGoalie")
                                        .HasColumnType("boolean")
                                        .HasColumnName("CompetitionRules_Roster_RequiresGoalie");

                                    b2.HasKey("HockeyCompetitionRulesHockeyCompetitionId");

                                    b2.ToTable("HockeyCompetitions", "hockey");

                                    b2.WithOwner()
                                        .HasForeignKey("HockeyCompetitionRulesHockeyCompetitionId");
                                });

                            b1.OwnsOne("Domain.ValueObjects.Hockey.Rules.HockeyStandingRules", "StandingRules", b2 =>
                                {
                                    b2.Property<Guid>("HockeyCompetitionRulesHockeyCompetitionId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("OvertimeLossPoints")
                                        .HasColumnType("integer")
                                        .HasColumnName("CompetitionRules_Standing_OvertimeLossPoints");

                                    b2.Property<int>("OvertimeWinPoints")
                                        .HasColumnType("integer")
                                        .HasColumnName("CompetitionRules_Standing_OvertimeWinPoints");

                                    b2.Property<int>("RegulationWinPoints")
                                        .HasColumnType("integer")
                                        .HasColumnName("CompetitionRules_Standing_RegulationWinPoints");

                                    b2.Property<int>("ShootoutLossPoints")
                                        .HasColumnType("integer")
                                        .HasColumnName("CompetitionRules_Standing_ShootoutLossPoints");

                                    b2.Property<int>("ShootoutWinPoints")
                                        .HasColumnType("integer")
                                        .HasColumnName("CompetitionRules_Standing_ShootoutWinPoints");

                                    b2.Property<int>("TiePoints")
                                        .HasColumnType("integer")
                                        .HasColumnName("CompetitionRules_Standing_TiePoints");

                                    b2.Property<string>("_tieBreakers")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("CompetitionRules_Standing_TieBreakers");

                                    b2.HasKey("HockeyCompetitionRulesHockeyCompetitionId");

                                    b2.ToTable("HockeyCompetitions", "hockey");

                                    b2.WithOwner()
                                        .HasForeignKey("HockeyCompetitionRulesHockeyCompetitionId");
                                });

                            b1.OwnsOne("Domain.ValueObjects.Hockey.Rules.HockeyVideoReviewRules", "VideoReviewRules", b2 =>
                                {
                                    b2.Property<Guid>("HockeyCompetitionRulesHockeyCompetitionId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("CoachChallengeAllowed")
                                        .HasColumnType("boolean")
                                        .HasColumnName("CompetitionRules_Video_CoachChallengeAllowed");

                                    b2.Property<bool>("Enabled")
                                        .HasColumnType("boolean")
                                        .HasColumnName("CompetitionRules_Video_Enabled");

                                    b2.Property<bool>("ReviewGoalieInterference")
                                        .HasColumnType("boolean")
                                        .HasColumnName("CompetitionRules_Video_ReviewGoalieInterference");

                                    b2.Property<bool>("ReviewGoals")
                                        .HasColumnType("boolean")
                                        .HasColumnName("CompetitionRules_Video_ReviewGoals");

                                    b2.Property<bool>("ReviewHighStickGoal")
                                        .HasColumnType("boolean")
                                        .HasColumnName("CompetitionRules_Video_ReviewHighStickGoal");

                                    b2.Property<bool>("ReviewOffsideBeforeGoal")
                                        .HasColumnType("boolean")
                                        .HasColumnName("CompetitionRules_Video_ReviewOffsideBeforeGoal");

                                    b2.Property<bool>("ReviewPuckOverLine")
                                        .HasColumnType("boolean")
                                        .HasColumnName("CompetitionRules_Video_ReviewPuckOverLine");

                                    b2.HasKey("HockeyCompetitionRulesHockeyCompetitionId");

                                    b2.ToTable("HockeyCompetitions", "hockey");

                                    b2.WithOwner()
                                        .HasForeignKey("HockeyCompetitionRulesHockeyCompetitionId");

                                    b2.OwnsOne("Domain.ValueObjects.Hockey.Rules.HockeyCoachChallengeRules", "CoachChallengeRules", b3 =>
                                        {
                                            b3.Property<Guid>("HockeyVideoReviewRulesHockeyCompetitionRulesHockeyCompetitionId")
                                                .HasColumnType("uuid");

                                            b3.Property<bool>("AllowChallengeInOvertime")
                                                .HasColumnType("boolean")
                                                .HasColumnName("CompetitionRules_Video_Challenge_AllowChallengeInOvertime");

                                            b3.Property<bool>("AllowChallengeInShootout")
                                                .HasColumnType("boolean")
                                                .HasColumnName("CompetitionRules_Video_Challenge_AllowChallengeInShootout");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("boolean")
                                                .HasColumnName("CompetitionRules_Video_Challenge_Enabled");

                                            b3.Property<int>("FailedChallengePenaltyMinutes")
                                                .HasColumnType("integer")
                                                .HasColumnName("CompetitionRules_Video_Challenge_FailedChallengePenaltyMinutes");

                                            b3.Property<string>("FailedChallengePenaltyOffence")
                                                .IsRequired()
                                                .HasColumnType("text")
                                                .HasColumnName("CompetitionRules_Video_Challenge_FailedChallengePenaltyOffence");

                                            b3.Property<string>("FailedChallengePenaltySeverity")
                                                .IsRequired()
                                                .HasColumnType("text")
                                                .HasColumnName("CompetitionRules_Video_Challenge_FailedChallengePenaltySeverity");

                                            b3.Property<bool>("LoseChallengeAfterFailed")
                                                .HasColumnType("boolean")
                                                .HasColumnName("CompetitionRules_Video_Challenge_LoseChallengeAfterFailed");

                                            b3.Property<int>("MaxChallengesPerTeam")
                                                .HasColumnType("integer")
                                                .HasColumnName("CompetitionRules_Video_Challenge_MaxChallengesPerTeam");

                                            b3.Property<bool>("PenaltyForFailedChallenge")
                                                .HasColumnType("boolean")
                                                .HasColumnName("CompetitionRules_Video_Challenge_PenaltyForFailedChallenge");

                                            b3.HasKey("HockeyVideoReviewRulesHockeyCompetitionRulesHockeyCompetitionId");

                                            b3.ToTable("HockeyCompetitions", "hockey");

                                            b3.WithOwner()
                                                .HasForeignKey("HockeyVideoReviewRulesHockeyCompetitionRulesHockeyCompetitionId");
                                        });

                                    b2.Navigation("CoachChallengeRules")
                                        .IsRequired();
                                });

                            b1.Navigation("ContactRules");

                            b1.Navigation("MatchRules")
                                .IsRequired();

                            b1.Navigation("RosterRules")
                                .IsRequired();

                            b1.Navigation("StandingRules")
                                .IsRequired();

                            b1.Navigation("VideoReviewRules");
                        });

                    b.Navigation("CompetitionRules")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Competitions.HockeyCompetitionDivision", b =>
                {
                    b.HasOne("Domain.Entities.Hockey.Competitions.HockeyCompetitionTeam", "ChampionCompetitionTeam")
                        .WithMany()
                        .HasForeignKey("ChampionCompetitionTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.Hockey.Competitions.HockeyCompetition", "Competition")
                        .WithMany("Divisions")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Domain.ValueObjects.Hockey.Rules.HockeyCompetitionRules", "RulesOverride", b1 =>
                        {
                            b1.Property<Guid>("HockeyCompetitionDivisionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("RulesOverride_Name");

                            b1.Property<string>("RuleBookSource")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("RulesOverride_RuleBookSource");

                            b1.Property<string>("RuleBookVersion")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("RulesOverride_RuleBookVersion");

                            b1.HasKey("HockeyCompetitionDivisionId");

                            b1.ToTable("HockeyCompetitionDivisions", "hockey");

                            b1.WithOwner()
                                .HasForeignKey("HockeyCompetitionDivisionId");

                            b1.OwnsOne("Domain.ValueObjects.Hockey.Rules.HockeyContactRules", "ContactRules", b2 =>
                                {
                                    b2.Property<Guid>("HockeyCompetitionRulesHockeyCompetitionDivisionId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("AutomaticGameMisconductForFight")
                                        .HasColumnType("boolean")
                                        .HasColumnName("RulesOverride_Contact_AutomaticGameMisconductForFight");

                                    b2.Property<bool>("BodyCheckingAllowed")
                                        .HasColumnType("boolean")
                                        .HasColumnName("RulesOverride_Contact_BodyCheckingAllowed");

                                    b2.Property<bool>("FightingAllowed")
                                        .HasColumnType("boolean")
                                        .HasColumnName("RulesOverride_Contact_FightingAllowed");

                                    b2.Property<bool>("OpenIceHitsAllowed")
                                        .HasColumnType("boolean")
                                        .HasColumnName("RulesOverride_Contact_OpenIceHitsAllowed");

                                    b2.Property<bool>("StrictHeadContactRule")
                                        .HasColumnType("boolean")
                                        .HasColumnName("RulesOverride_Contact_StrictHeadContactRule");

                                    b2.HasKey("HockeyCompetitionRulesHockeyCompetitionDivisionId");

                                    b2.ToTable("HockeyCompetitionDivisions", "hockey");

                                    b2.WithOwner()
                                        .HasForeignKey("HockeyCompetitionRulesHockeyCompetitionDivisionId");
                                });

                            b1.OwnsOne("Domain.ValueObjects.Hockey.Rules.HockeyMatchRules", "MatchRules", b2 =>
                                {
                                    b2.Property<Guid>("HockeyCompetitionRulesHockeyCompetitionDivisionId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("DelayedOffsideEnabled")
                                        .HasColumnType("boolean")
                                        .HasColumnName("RulesOverride_Match_DelayedOffsideEnabled");

                                    b2.Property<bool>("GoaliePullAllowed")
                                        .HasColumnType("boolean")
                                        .HasColumnName("RulesOverride_Match_GoaliePullAllowed");

                                    b2.Property<string>("IcingRule")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("RulesOverride_Match_IcingRule");

                                    b2.Property<bool>("OffsideEnabled")
                                        .HasColumnType("boolean")
                                        .HasColumnName("RulesOverride_Match_OffsideEnabled");

                                    b2.Property<bool>("OvertimeEnabled")
                                        .HasColumnType("boolean")
                                        .HasColumnName("RulesOverride_Match_OvertimeEnabled");

                                    b2.Property<int>("OvertimeLengthMinutes")
                                        .HasColumnType("integer")
                                        .HasColumnName("RulesOverride_Match_OvertimeLengthMinutes");

                                    b2.Property<bool>("PenaltyShotEnabled")
                                        .HasColumnType("boolean")
                                        .HasColumnName("RulesOverride_Match_PenaltyShotEnabled");

                                    b2.Property<int>("RegularPeriodCount")
                                        .HasColumnType("integer")
                                        .HasColumnName("RulesOverride_Match_RegularPeriodCount");

                                    b2.Property<int>("RegularPeriodLengthMinutes")
                                        .HasColumnType("integer")
                                        .HasColumnName("RulesOverride_Match_RegularPeriodLengthMinutes");

                                    b2.Property<bool>("ShootoutEnabled")
                                        .HasColumnType("boolean")
                                        .HasColumnName("RulesOverride_Match_ShootoutEnabled");

                                    b2.Property<bool>("StopClock")
                                        .HasColumnType("boolean")
                                        .HasColumnName("RulesOverride_Match_StopClock");

                                    b2.HasKey("HockeyCompetitionRulesHockeyCompetitionDivisionId");

                                    b2.ToTable("HockeyCompetitionDivisions", "hockey");

                                    b2.WithOwner()
                                        .HasForeignKey("HockeyCompetitionRulesHockeyCompetitionDivisionId");
                                });

                            b1.OwnsOne("Domain.ValueObjects.Hockey.Rules.HockeyRosterRules", "RosterRules", b2 =>
                                {
                                    b2.Property<Guid>("HockeyCompetitionRulesHockeyCompetitionDivisionId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("AllowGuestPlayers")
                                        .HasColumnType("boolean")
                                        .HasColumnName("RulesOverride_Roster_AllowGuestPlayers");

                                    b2.Property<bool>("CanGoalieBeCaptain")
                                        .HasColumnType("boolean")
                                        .HasColumnName("RulesOverride_Roster_CanGoalieBeCaptain");

                                    b2.Property<bool>("LineManagementEnabled")
                                        .HasColumnType("boolean")
                                        .HasColumnName("RulesOverride_Roster_LineManagementEnabled");

                                    b2.Property<int>("MaxAlternateCaptains")
                                        .HasColumnType("integer")
                                        .HasColumnName("RulesOverride_Roster_MaxAlternateCaptains");

                                    b2.Property<int>("MaxCaptains")
                                        .HasColumnType("integer")
                                        .HasColumnName("RulesOverride_Roster_MaxCaptains");

                                    b2.Property<int>("MaxDressedGoalies")
                                        .HasColumnType("integer")
                                        .HasColumnName("RulesOverride_Roster_MaxDressedGoalies");

                                    b2.Property<int>("MaxDressedPlayers")
                                        .HasColumnType("integer")
                                        .HasColumnName("RulesOverride_Roster_MaxDressedPlayers");

                                    b2.Property<int>("MinDressedPlayers")
                                        .HasColumnType("integer")
                                        .HasColumnName("RulesOverride_Roster_MinDressedPlayers");

                                    b2.Property<bool>("RequiresGoalie")
                                        .HasColumnType("boolean")
                                        .HasColumnName("RulesOverride_Roster_RequiresGoalie");

                                    b2.HasKey("HockeyCompetitionRulesHockeyCompetitionDivisionId");

                                    b2.ToTable("HockeyCompetitionDivisions", "hockey");

                                    b2.WithOwner()
                                        .HasForeignKey("HockeyCompetitionRulesHockeyCompetitionDivisionId");
                                });

                            b1.OwnsOne("Domain.ValueObjects.Hockey.Rules.HockeyStandingRules", "StandingRules", b2 =>
                                {
                                    b2.Property<Guid>("HockeyCompetitionRulesHockeyCompetitionDivisionId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("OvertimeLossPoints")
                                        .HasColumnType("integer")
                                        .HasColumnName("RulesOverride_Standing_OvertimeLossPoints");

                                    b2.Property<int>("OvertimeWinPoints")
                                        .HasColumnType("integer")
                                        .HasColumnName("RulesOverride_Standing_OvertimeWinPoints");

                                    b2.Property<int>("RegulationWinPoints")
                                        .HasColumnType("integer")
                                        .HasColumnName("RulesOverride_Standing_RegulationWinPoints");

                                    b2.Property<int>("ShootoutLossPoints")
                                        .HasColumnType("integer")
                                        .HasColumnName("RulesOverride_Standing_ShootoutLossPoints");

                                    b2.Property<int>("ShootoutWinPoints")
                                        .HasColumnType("integer")
                                        .HasColumnName("RulesOverride_Standing_ShootoutWinPoints");

                                    b2.Property<int>("TiePoints")
                                        .HasColumnType("integer")
                                        .HasColumnName("RulesOverride_Standing_TiePoints");

                                    b2.Property<string>("_tieBreakers")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("RulesOverride_Standing_TieBreakers");

                                    b2.HasKey("HockeyCompetitionRulesHockeyCompetitionDivisionId");

                                    b2.ToTable("HockeyCompetitionDivisions", "hockey");

                                    b2.WithOwner()
                                        .HasForeignKey("HockeyCompetitionRulesHockeyCompetitionDivisionId");
                                });

                            b1.OwnsOne("Domain.ValueObjects.Hockey.Rules.HockeyVideoReviewRules", "VideoReviewRules", b2 =>
                                {
                                    b2.Property<Guid>("HockeyCompetitionRulesHockeyCompetitionDivisionId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("CoachChallengeAllowed")
                                        .HasColumnType("boolean")
                                        .HasColumnName("RulesOverride_Video_CoachChallengeAllowed");

                                    b2.Property<bool>("Enabled")
                                        .HasColumnType("boolean")
                                        .HasColumnName("RulesOverride_Video_Enabled");

                                    b2.Property<bool>("ReviewGoalieInterference")
                                        .HasColumnType("boolean")
                                        .HasColumnName("RulesOverride_Video_ReviewGoalieInterference");

                                    b2.Property<bool>("ReviewGoals")
                                        .HasColumnType("boolean")
                                        .HasColumnName("RulesOverride_Video_ReviewGoals");

                                    b2.Property<bool>("ReviewHighStickGoal")
                                        .HasColumnType("boolean")
                                        .HasColumnName("RulesOverride_Video_ReviewHighStickGoal");

                                    b2.Property<bool>("ReviewOffsideBeforeGoal")
                                        .HasColumnType("boolean")
                                        .HasColumnName("RulesOverride_Video_ReviewOffsideBeforeGoal");

                                    b2.Property<bool>("ReviewPuckOverLine")
                                        .HasColumnType("boolean")
                                        .HasColumnName("RulesOverride_Video_ReviewPuckOverLine");

                                    b2.HasKey("HockeyCompetitionRulesHockeyCompetitionDivisionId");

                                    b2.ToTable("HockeyCompetitionDivisions", "hockey");

                                    b2.WithOwner()
                                        .HasForeignKey("HockeyCompetitionRulesHockeyCompetitionDivisionId");

                                    b2.OwnsOne("Domain.ValueObjects.Hockey.Rules.HockeyCoachChallengeRules", "CoachChallengeRules", b3 =>
                                        {
                                            b3.Property<Guid>("HockeyVideoReviewRulesHockeyCompetitionRulesHockeyCompetitionDivisionId")
                                                .HasColumnType("uuid")
                                                .HasColumnName("HockeyVideoReviewRulesHockeyCompetitionRulesHockeyCompetitionD~");

                                            b3.Property<bool>("AllowChallengeInOvertime")
                                                .HasColumnType("boolean")
                                                .HasColumnName("RulesOverride_Video_Challenge_AllowChallengeInOvertime");

                                            b3.Property<bool>("AllowChallengeInShootout")
                                                .HasColumnType("boolean")
                                                .HasColumnName("RulesOverride_Video_Challenge_AllowChallengeInShootout");

                                            b3.Property<bool>("Enabled")
                                                .HasColumnType("boolean")
                                                .HasColumnName("RulesOverride_Video_Challenge_Enabled");

                                            b3.Property<int>("FailedChallengePenaltyMinutes")
                                                .HasColumnType("integer")
                                                .HasColumnName("RulesOverride_Video_Challenge_FailedChallengePenaltyMinutes");

                                            b3.Property<string>("FailedChallengePenaltyOffence")
                                                .IsRequired()
                                                .HasColumnType("text")
                                                .HasColumnName("RulesOverride_Video_Challenge_FailedChallengePenaltyOffence");

                                            b3.Property<string>("FailedChallengePenaltySeverity")
                                                .IsRequired()
                                                .HasColumnType("text")
                                                .HasColumnName("RulesOverride_Video_Challenge_FailedChallengePenaltySeverity");

                                            b3.Property<bool>("LoseChallengeAfterFailed")
                                                .HasColumnType("boolean")
                                                .HasColumnName("RulesOverride_Video_Challenge_LoseChallengeAfterFailed");

                                            b3.Property<int>("MaxChallengesPerTeam")
                                                .HasColumnType("integer")
                                                .HasColumnName("RulesOverride_Video_Challenge_MaxChallengesPerTeam");

                                            b3.Property<bool>("PenaltyForFailedChallenge")
                                                .HasColumnType("boolean")
                                                .HasColumnName("RulesOverride_Video_Challenge_PenaltyForFailedChallenge");

                                            b3.HasKey("HockeyVideoReviewRulesHockeyCompetitionRulesHockeyCompetitionDivisionId");

                                            b3.ToTable("HockeyCompetitionDivisions", "hockey");

                                            b3.WithOwner()
                                                .HasForeignKey("HockeyVideoReviewRulesHockeyCompetitionRulesHockeyCompetitionDivisionId");
                                        });

                                    b2.Navigation("CoachChallengeRules")
                                        .IsRequired();
                                });

                            b1.Navigation("ContactRules");

                            b1.Navigation("MatchRules")
                                .IsRequired();

                            b1.Navigation("RosterRules")
                                .IsRequired();

                            b1.Navigation("StandingRules")
                                .IsRequired();

                            b1.Navigation("VideoReviewRules");
                        });

                    b.Navigation("ChampionCompetitionTeam");

                    b.Navigation("Competition");

                    b.Navigation("RulesOverride");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Competitions.HockeyCompetitionDivisionTeam", b =>
                {
                    b.HasOne("Domain.Entities.Hockey.Competitions.HockeyCompetitionDivision", "CompetitionDivision")
                        .WithMany("Teams")
                        .HasForeignKey("CompetitionDivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Hockey.Competitions.HockeyCompetitionTeam", "CompetitionTeam")
                        .WithMany()
                        .HasForeignKey("CompetitionTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompetitionDivision");

                    b.Navigation("CompetitionTeam");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Competitions.HockeyCompetitionTeam", b =>
                {
                    b.HasOne("Domain.Entities.Hockey.Competitions.HockeyCompetition", "Competition")
                        .WithMany("Teams")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Competitions.HockeyPlayoffSeries", b =>
                {
                    b.HasOne("Domain.Entities.Hockey.Competitions.HockeyCompetitionTeam", "AwayCompetitionTeam")
                        .WithMany()
                        .HasForeignKey("AwayCompetitionTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.Hockey.Competitions.HockeyCompetition", "Competition")
                        .WithMany("PlayoffSeries")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Hockey.Competitions.HockeyCompetitionTeam", "HomeCompetitionTeam")
                        .WithMany()
                        .HasForeignKey("HomeCompetitionTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Domain.Entities.Hockey.Competitions.HockeyCompetitionTeam", "WinnerCompetitionTeam")
                        .WithMany()
                        .HasForeignKey("WinnerCompetitionTeamId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AwayCompetitionTeam");

                    b.Navigation("Competition");

                    b.Navigation("HomeCompetitionTeam");

                    b.Navigation("WinnerCompetitionTeam");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Competitions.HockeyTournamentGroup", b =>
                {
                    b.HasOne("Domain.Entities.Hockey.Competitions.HockeyTournament", "Tournament")
                        .WithMany("Groups")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Competitions.HockeyTournamentGroupTeam", b =>
                {
                    b.HasOne("Domain.Entities.Hockey.Competitions.HockeyCompetitionTeam", "CompetitionTeam")
                        .WithMany()
                        .HasForeignKey("CompetitionTeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Hockey.Competitions.HockeyTournamentGroup", "TournamentGroup")
                        .WithMany("Teams")
                        .HasForeignKey("TournamentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CompetitionTeam");

                    b.Navigation("TournamentGroup");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Matches.HockeyMatch", b =>
                {
                    b.HasOne("Domain.Entities.Hockey.Competitions.HockeyCompetition", null)
                        .WithMany("Matches")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Teams.HockeyLine", b =>
                {
                    b.HasOne("Domain.Entities.Hockey.Teams.HockeyTeam", "Team")
                        .WithMany("Lines")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Teams.HockeyLinePlayer", b =>
                {
                    b.HasOne("Domain.Entities.Hockey.Teams.HockeyLine", "Line")
                        .WithMany("Players")
                        .HasForeignKey("LineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Hockey.Teams.HockeyTeamPlayer", null)
                        .WithMany()
                        .HasForeignKey("TeamPlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Line");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Teams.HockeyTeamPlayer", b =>
                {
                    b.HasOne("Domain.Entities.Hockey.Teams.HockeyPlayer", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Hockey.Teams.HockeyTeam", "Team")
                        .WithMany("Roster")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Teams.HockeyTeamStaff", b =>
                {
                    b.HasOne("Domain.Entities.Hockey.Teams.HockeyTeam", "Team")
                        .WithMany("StaffMembers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Competitions.HockeyTournament", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Hockey.Rules.HockeyTournamentRules", "TournamentRules", b1 =>
                        {
                            b1.Property<Guid>("HockeyTournamentId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Format")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("TournamentRules_Format");

                            b1.Property<bool>("HasBronzeGame")
                                .HasColumnType("boolean")
                                .HasColumnName("TournamentRules_HasBronzeGame");

                            b1.Property<bool>("HasGroupStage")
                                .HasColumnType("boolean")
                                .HasColumnName("TournamentRules_HasGroupStage");

                            b1.Property<bool>("HasPlacementGames")
                                .HasColumnType("boolean")
                                .HasColumnName("TournamentRules_HasPlacementGames");

                            b1.Property<bool>("HasPlayoffs")
                                .HasColumnType("boolean")
                                .HasColumnName("TournamentRules_HasPlayoffs");

                            b1.Property<int>("TeamsAdvancingPerGroup")
                                .HasColumnType("integer")
                                .HasColumnName("TournamentRules_TeamsAdvancingPerGroup");

                            b1.HasKey("HockeyTournamentId");

                            b1.ToTable("HockeyCompetitions", "hockey");

                            b1.WithOwner()
                                .HasForeignKey("HockeyTournamentId");

                            b1.OwnsOne("Domain.ValueObjects.Hockey.Rules.HockeyStandingRules", "GroupStandingRules", b2 =>
                                {
                                    b2.Property<Guid>("HockeyTournamentRulesHockeyTournamentId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("OvertimeLossPoints")
                                        .HasColumnType("integer")
                                        .HasColumnName("TournamentRules_GroupStanding_OvertimeLossPoints");

                                    b2.Property<int>("OvertimeWinPoints")
                                        .HasColumnType("integer")
                                        .HasColumnName("TournamentRules_GroupStanding_OvertimeWinPoints");

                                    b2.Property<int>("RegulationWinPoints")
                                        .HasColumnType("integer")
                                        .HasColumnName("TournamentRules_GroupStanding_RegulationWinPoints");

                                    b2.Property<int>("ShootoutLossPoints")
                                        .HasColumnType("integer")
                                        .HasColumnName("TournamentRules_GroupStanding_ShootoutLossPoints");

                                    b2.Property<int>("ShootoutWinPoints")
                                        .HasColumnType("integer")
                                        .HasColumnName("TournamentRules_GroupStanding_ShootoutWinPoints");

                                    b2.Property<int>("TiePoints")
                                        .HasColumnType("integer")
                                        .HasColumnName("TournamentRules_GroupStanding_TiePoints");

                                    b2.HasKey("HockeyTournamentRulesHockeyTournamentId");

                                    b2.ToTable("HockeyCompetitions", "hockey");

                                    b2.WithOwner()
                                        .HasForeignKey("HockeyTournamentRulesHockeyTournamentId");
                                });

                            b1.OwnsOne("Domain.ValueObjects.Hockey.Rules.HockeyMatchRules", "MatchRulesOverride", b2 =>
                                {
                                    b2.Property<Guid>("HockeyTournamentRulesHockeyTournamentId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("DelayedOffsideEnabled")
                                        .HasColumnType("boolean")
                                        .HasColumnName("TournamentRules_MatchOverride_DelayedOffsideEnabled");

                                    b2.Property<bool>("GoaliePullAllowed")
                                        .HasColumnType("boolean")
                                        .HasColumnName("TournamentRules_MatchOverride_GoaliePullAllowed");

                                    b2.Property<string>("IcingRule")
                                        .IsRequired()
                                        .HasColumnType("text")
                                        .HasColumnName("TournamentRules_MatchOverride_IcingRule");

                                    b2.Property<bool>("OffsideEnabled")
                                        .HasColumnType("boolean")
                                        .HasColumnName("TournamentRules_MatchOverride_OffsideEnabled");

                                    b2.Property<bool>("OvertimeEnabled")
                                        .HasColumnType("boolean")
                                        .HasColumnName("TournamentRules_MatchOverride_OvertimeEnabled");

                                    b2.Property<int>("OvertimeLengthMinutes")
                                        .HasColumnType("integer")
                                        .HasColumnName("TournamentRules_MatchOverride_OvertimeLengthMinutes");

                                    b2.Property<bool>("PenaltyShotEnabled")
                                        .HasColumnType("boolean")
                                        .HasColumnName("TournamentRules_MatchOverride_PenaltyShotEnabled");

                                    b2.Property<int>("RegularPeriodCount")
                                        .HasColumnType("integer")
                                        .HasColumnName("TournamentRules_MatchOverride_RegularPeriodCount");

                                    b2.Property<int>("RegularPeriodLengthMinutes")
                                        .HasColumnType("integer")
                                        .HasColumnName("TournamentRules_MatchOverride_RegularPeriodLengthMinutes");

                                    b2.Property<bool>("ShootoutEnabled")
                                        .HasColumnType("boolean")
                                        .HasColumnName("TournamentRules_MatchOverride_ShootoutEnabled");

                                    b2.Property<bool>("StopClock")
                                        .HasColumnType("boolean")
                                        .HasColumnName("TournamentRules_MatchOverride_StopClock");

                                    b2.HasKey("HockeyTournamentRulesHockeyTournamentId");

                                    b2.ToTable("HockeyCompetitions", "hockey");

                                    b2.WithOwner()
                                        .HasForeignKey("HockeyTournamentRulesHockeyTournamentId");
                                });

                            b1.Navigation("GroupStandingRules");

                            b1.Navigation("MatchRulesOverride");
                        });

                    b.Navigation("TournamentRules")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Competitions.HockeyCompetition", b =>
                {
                    b.Navigation("Divisions");

                    b.Navigation("Matches");

                    b.Navigation("PlayoffSeries");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Competitions.HockeyCompetitionDivision", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Competitions.HockeyTournamentGroup", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Teams.HockeyLine", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Teams.HockeyTeam", b =>
                {
                    b.Navigation("Lines");

                    b.Navigation("Roster");

                    b.Navigation("StaffMembers");
                });

            modelBuilder.Entity("Domain.Entities.Hockey.Competitions.HockeyTournament", b =>
                {
                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
