// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyLeague.Infrastructure.Persistence.Contexts;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyLeague.Infrastructure.Migrations.FootballDb
{
    [DbContext(typeof(FootballDbContext))]
    [Migration("20260813110757_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("football")
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Football.Competitions.FootballCompetition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CompetitionType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TeamCategory")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Adult");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TeamCategory");

                    b.ToTable("FootballCompetitions", "football");

                    b.HasDiscriminator<string>("CompetitionType").HasValue("FootballCompetition");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Football.Competitions.FootballCompetitionDivision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DivisionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId", "DivisionId")
                        .IsUnique()
                        .HasDatabaseName("IX_FootballSeasonDivisions_Season_Division");

                    b.ToTable("FootballSeasonDivisions", "football");
                });

            modelBuilder.Entity("Domain.Entities.Football.Competitions.FootballCompetitionDivisionTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionDivisionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("CompetitionDivisionId", "TeamId")
                        .IsUnique()
                        .HasDatabaseName("IX_FootballSeasonDivisionTeams_SeasonDivision_Team");

                    b.HasIndex("CompetitionId", "TeamId")
                        .IsUnique()
                        .HasDatabaseName("IX_FootballSeasonDivisionTeams_Season_Team");

                    b.ToTable("FootballSeasonDivisionTeams", "football");
                });

            modelBuilder.Entity("Domain.Entities.Football.Competitions.FootballTournamentGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<Guid>("TournamentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId", "Order")
                        .HasDatabaseName("IX_FootballTournamentGroups_Tournament_Order");

                    b.ToTable("FootballTournamentGroups", "football");
                });

            modelBuilder.Entity("Domain.Entities.Football.Competitions.FootballTournamentGroupTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TournamentGroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("TournamentGroupId", "TeamId")
                        .IsUnique()
                        .HasDatabaseName("IX_FootballTournamentGroupTeams_Group_Team");

                    b.ToTable("FootballTournamentGroupTeams", "football");
                });

            modelBuilder.Entity("Domain.Entities.Football.Matches.FootballMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AwayScore")
                        .HasColumnType("integer");

                    b.Property<Guid?>("AwayTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HomeScore")
                        .HasColumnType("integer");

                    b.Property<Guid?>("HomeTeamId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("NextMatchId")
                        .HasColumnType("uuid");

                    b.Property<int?>("NextMatchSlot")
                        .HasColumnType("integer");

                    b.Property<int?>("PlayoffMatchOrder")
                        .HasColumnType("integer");

                    b.Property<int?>("PlayoffRound")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledDateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TournamentGroupId")
                        .HasColumnType("uuid");

                    b.Property<int?>("TournamentStage")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Venue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("WentToExtraTime")
                        .HasColumnType("boolean");

                    b.Property<bool>("WentToPenaltyShootout")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("CompetitionId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("NextMatchId");

                    b.HasIndex("TournamentGroupId");

                    b.ToTable("FootballMatches", "football");
                });

            modelBuilder.Entity("Domain.Entities.Football.Matches.FootballMatchEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("PeriodNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("TimeInSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MatchId")
                        .HasDatabaseName("IX_FootballMatchEvent_MatchId");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("IX_FootballMatchEvent_TeamId");

                    b.HasIndex("MatchId", "PeriodNumber", "TimeInSeconds")
                        .HasDatabaseName("IX_FootballMatchEvent_MatchId_Period_Time");

                    b.ToTable("FootballMatchEvents", "football", t =>
                        {
                            t.HasCheckConstraint("CK_FootballMatchEvent_PeriodNumber", "\"PeriodNumber\" > 0");

                            t.HasCheckConstraint("CK_FootballMatchEvent_TimeInSeconds", "\"TimeInSeconds\" >= 0");
                        });

                    b.HasDiscriminator<string>("EventType").HasValue("FootballMatchEvent");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Domain.Entities.Football.Matches.FootballMatchLineupPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the entity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was created");

                    b.Property<bool>("IsOnField")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsSentOff")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was last updated");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_FootballMatchLineupPlayer_CreatedAt");

                    b.HasIndex("PlayerId");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_FootballMatchLineupPlayer_UpdatedAt")
                        .HasFilter("\"UpdatedAt\" IS NOT NULL");

                    b.HasIndex("CreatedAt", "UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_FootballMatchLineupPlayer_Audit");

                    b.HasIndex("MatchId", "TeamId", "PlayerId")
                        .IsUnique()
                        .HasDatabaseName("IX_FootballMatchLineupPlayer_Match_Team_Player");

                    b.ToTable("FootballMatchLineupPlayers", "football");
                });

            modelBuilder.Entity("Domain.Entities.Football.Matches.FootballPeriodScore", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the entity");

                    b.Property<int>("AwayScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("AwayTeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was created");

                    b.Property<int>("HomeScore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("HomeTeamId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("PeriodNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was last updated");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_FootballPeriodScore_CreatedAt");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_FootballPeriodScore_UpdatedAt")
                        .HasFilter("\"UpdatedAt\" IS NOT NULL");

                    b.HasIndex("CreatedAt", "UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_FootballPeriodScore_Audit");

                    b.HasIndex("MatchId", "PeriodNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_FootballPeriodScore_Match_Period");

                    b.ToTable("FootballPeriodScores", "football");
                });

            modelBuilder.Entity("Domain.Entities.Football.Statistics.FootballMatchTeamStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("CleanSheet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Goals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("MatchId")
                        .HasColumnType("uuid");

                    b.Property<int>("RedCards")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Substitutions")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("YellowCards")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("MatchId", "TeamId")
                        .IsUnique()
                        .HasDatabaseName("IX_FootballMatchTeamStatistics_Match_Team");

                    b.ToTable("FootballMatchTeamStatistics", "football");
                });

            modelBuilder.Entity("Domain.Entities.Football.Statistics.FootballPlayerSeasonStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Assists")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GamesPlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Goals")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("RedCards")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("YellowCards")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId", "Goals")
                        .HasDatabaseName("IX_FootballPlayerSeasonStatistics_Competition_Goals");

                    b.HasIndex("PlayerId", "TeamId", "CompetitionId")
                        .IsUnique()
                        .HasDatabaseName("IX_FootballPlayerSeasonStatistics_Player_Team_Competition");

                    b.ToTable("FootballPlayerSeasonStatistics", "football");
                });

            modelBuilder.Entity("Domain.Entities.Football.Statistics.FootballStatisticsCache", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CacheKey")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("JsonData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CacheKey")
                        .IsUnique()
                        .HasDatabaseName("IX_FootballStatisticsCache_CacheKey");

                    b.ToTable("FootballStatisticsCache", "football");
                });

            modelBuilder.Entity("Domain.Entities.Football.Statistics.FootballTeamSeasonStatistics", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AwayLosses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("AwayWins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("CleanSheets")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("CompetitionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Draws")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("GamesPlayed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("GoalDifference")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("GoalsAgainst")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("GoalsFor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("HomeLosses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("HomeWins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Losses")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("Points")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("RedCards")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Wins")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("YellowCards")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("TeamId", "CompetitionId")
                        .IsUnique()
                        .HasDatabaseName("IX_FootballTeamSeasonStatistics_Team_Competition");

                    b.ToTable("FootballTeamSeasonStatistics", "football");
                });

            modelBuilder.Entity("Domain.Entities.Football.Teams.FootballPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CareerAssists")
                        .HasColumnType("integer");

                    b.Property<int>("CareerGoals")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FootballPlayers", "football");
                });

            modelBuilder.Entity("Domain.Entities.Football.Teams.FootballReferee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LicenseExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LicenseIssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MatchesOfficiated")
                        .HasColumnType("integer");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FootballReferees", "football");
                });

            modelBuilder.Entity("Domain.Entities.Football.Teams.FootballTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ClubId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DivisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("HomeArena")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PrimaryJerseyColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SecondaryJerseyColor")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TeamCategory")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("FootballTeams", "football");
                });

            modelBuilder.Entity("Domain.Entities.Football.Teams.FootballTeamManager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("IX_FootballTeamManager_PersonId");

                    b.HasIndex("TeamId")
                        .HasDatabaseName("IX_FootballTeamManager_TeamId");

                    b.ToTable("FootballTeamManagers", "football");
                });

            modelBuilder.Entity("Domain.Entities.Football.Teams.FootballTeamPlayer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasComment("Unique identifier for the entity");

                    b.Property<int>("Assists")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was created");

                    b.Property<int>("GamesPlayed")
                        .HasColumnType("integer");

                    b.Property<int>("Goals")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int?>("JerseyNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RedCards")
                        .HasColumnType("integer");

                    b.Property<int?>("RequestedJerseyNumber")
                        .HasColumnType("integer");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasComment("UTC timestamp when the entity was last updated");

                    b.Property<int>("YellowCards")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_FootballTeamPlayer_CreatedAt");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_FootballTeamPlayer_PlayerId");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("IX_FootballTeamPlayer_UpdatedAt")
                        .HasFilter("\"UpdatedAt\" IS NOT NULL");

                    b.HasIndex("CreatedAt", "UpdatedAt")
                        .IsDescending()
                        .HasDatabaseName("IX_FootballTeamPlayer_Audit");

                    b.HasIndex("TeamId", "JerseyNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_FootballTeamPlayer_TeamId_JerseyNumber")
                        .HasFilter("\"JerseyNumber\" IS NOT NULL");

                    b.HasIndex("TeamId", "PlayerId")
                        .IsUnique()
                        .HasDatabaseName("IX_FootballTeamPlayer_TeamId_PlayerId");

                    b.ToTable("FootballTeamPlayers", "football");
                });

            modelBuilder.Entity("FootballCompetitionTeam", b =>
                {
                    b.Property<Guid>("CompetitionsId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TeamsId")
                        .HasColumnType("uuid");

                    b.HasKey("CompetitionsId", "TeamsId");

                    b.HasIndex("TeamsId");

                    b.ToTable("FootballCompetitionTeam", "football");
                });

            modelBuilder.Entity("FootballMatchOfficial", b =>
                {
                    b.Property<Guid>("MatchesId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OfficialsId")
                        .HasColumnType("uuid");

                    b.HasKey("MatchesId", "OfficialsId");

                    b.HasIndex("OfficialsId");

                    b.ToTable("FootballMatchOfficial", "football");
                });

            modelBuilder.Entity("Domain.Entities.Football.Competitions.FootballSeason", b =>
                {
                    b.HasBaseType("Domain.Entities.Football.Competitions.FootballCompetition");

                    b.HasDiscriminator().HasValue("Season");
                });

            modelBuilder.Entity("Domain.Entities.Football.Competitions.FootballTournament", b =>
                {
                    b.HasBaseType("Domain.Entities.Football.Competitions.FootballCompetition");

                    b.Property<Guid?>("ChampionTeamId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHtml")
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)");

                    b.Property<int>("TournamentStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Venue")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("_playoffSchedule")
                        .HasColumnType("jsonb")
                        .HasColumnName("PlayoffSchedule");

                    b.HasDiscriminator().HasValue("Tournament");
                });

            modelBuilder.Entity("Domain.Entities.Football.Matches.FootballCard", b =>
                {
                    b.HasBaseType("Domain.Entities.Football.Matches.FootballMatchEvent");

                    b.Property<string>("CardType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("IX_FootballMatchEvent_CardPlayerId");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_FootballMatchEvent_PeriodNumber", "\"PeriodNumber\" > 0");

                            t.HasCheckConstraint("CK_FootballMatchEvent_TimeInSeconds", "\"TimeInSeconds\" >= 0");
                        });

                    b.HasDiscriminator().HasValue("Card");
                });

            modelBuilder.Entity("Domain.Entities.Football.Matches.FootballGoal", b =>
                {
                    b.HasBaseType("Domain.Entities.Football.Matches.FootballMatchEvent");

                    b.Property<Guid?>("AssistingPlayerId")
                        .HasColumnType("uuid");

                    b.Property<int?>("GoalType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ScoringPlayerId")
                        .HasColumnType("uuid");

                    b.HasIndex("AssistingPlayerId")
                        .HasDatabaseName("IX_FootballMatchEvent_AssistingPlayerId");

                    b.HasIndex("ScoringPlayerId")
                        .HasDatabaseName("IX_FootballMatchEvent_ScoringPlayerId");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_FootballMatchEvent_PeriodNumber", "\"PeriodNumber\" > 0");

                            t.HasCheckConstraint("CK_FootballMatchEvent_TimeInSeconds", "\"TimeInSeconds\" >= 0");
                        });

                    b.HasDiscriminator().HasValue("Goal");
                });

            modelBuilder.Entity("Domain.Entities.Football.Matches.FootballSubstitution", b =>
                {
                    b.HasBaseType("Domain.Entities.Football.Matches.FootballMatchEvent");

                    b.Property<Guid>("PlayerOffId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PlayerOnId")
                        .HasColumnType("uuid");

                    b.HasIndex("PlayerOffId")
                        .HasDatabaseName("IX_FootballMatchEvent_PlayerOffId");

                    b.HasIndex("PlayerOnId")
                        .HasDatabaseName("IX_FootballMatchEvent_PlayerOnId");

                    b.ToTable(t =>
                        {
                            t.HasCheckConstraint("CK_FootballMatchEvent_PeriodNumber", "\"PeriodNumber\" > 0");

                            t.HasCheckConstraint("CK_FootballMatchEvent_TimeInSeconds", "\"TimeInSeconds\" >= 0");
                        });

                    b.HasDiscriminator().HasValue("Substitution");
                });

            modelBuilder.Entity("Domain.Entities.Football.Competitions.FootballCompetition", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Football.FootballMatchRules", "MatchRules", b1 =>
                        {
                            b1.Property<Guid>("FootballCompetitionId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("AllowExtraTime")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("MatchRules_AllowExtraTime");

                            b1.Property<bool>("AllowPenaltyShootout")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("MatchRules_AllowPenaltyShootout");

                            b1.Property<int>("ExtraTimeHalfCount")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("MatchRules_ExtraTimeHalfCount");

                            b1.Property<int>("ExtraTimeHalfDurationMinutes")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("MatchRules_ExtraTimeHalfDurationMinutes");

                            b1.Property<int>("HalfDurationMinutes")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(45)
                                .HasColumnName("MatchRules_HalfDurationMinutes");

                            b1.Property<int>("MaxSubstitutions")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("MatchRules_MaxSubstitutions");

                            b1.Property<int>("NumberOfHalves")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(2)
                                .HasColumnName("MatchRules_NumberOfHalves");

                            b1.Property<int>("PlayersOnField")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(11)
                                .HasColumnName("MatchRules_PlayersOnField");

                            b1.Property<bool>("RequireGoalkeeper")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("MatchRules_RequireGoalkeeper");

                            b1.Property<bool>("RequireOfficialsToStart")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("MatchRules_RequireOfficialsToStart");

                            b1.HasKey("FootballCompetitionId");

                            b1.ToTable("FootballCompetitions", "football");

                            b1.WithOwner()
                                .HasForeignKey("FootballCompetitionId");
                        });

                    b.OwnsOne("Domain.ValueObjects.Football.FootballStandingRules", "StandingRules", b1 =>
                        {
                            b1.Property<Guid>("FootballCompetitionId")
                                .HasColumnType("uuid");

                            b1.Property<int>("DrawPoints")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(1)
                                .HasColumnName("StandingRules_DrawPoints");

                            b1.Property<int>("LossPoints")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("StandingRules_LossPoints");

                            b1.Property<int>("WinPoints")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(3)
                                .HasColumnName("StandingRules_WinPoints");

                            b1.HasKey("FootballCompetitionId");

                            b1.ToTable("FootballCompetitions", "football");

                            b1.WithOwner()
                                .HasForeignKey("FootballCompetitionId");
                        });

                    b.Navigation("MatchRules")
                        .IsRequired();

                    b.Navigation("StandingRules")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Football.Competitions.FootballCompetitionDivision", b =>
                {
                    b.HasOne("Domain.Entities.Football.Competitions.FootballCompetition", "Competition")
                        .WithMany()
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Competition");
                });

            modelBuilder.Entity("Domain.Entities.Football.Competitions.FootballCompetitionDivisionTeam", b =>
                {
                    b.HasOne("Domain.Entities.Football.Competitions.FootballCompetitionDivision", "CompetitionDivision")
                        .WithMany("Teams")
                        .HasForeignKey("CompetitionDivisionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Football.Teams.FootballTeam", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompetitionDivision");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Domain.Entities.Football.Competitions.FootballTournamentGroup", b =>
                {
                    b.HasOne("Domain.Entities.Football.Competitions.FootballTournament", null)
                        .WithMany("Groups")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Football.Competitions.FootballTournamentGroupTeam", b =>
                {
                    b.HasOne("Domain.Entities.Football.Teams.FootballTeam", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Football.Competitions.FootballTournamentGroup", "TournamentGroup")
                        .WithMany("Teams")
                        .HasForeignKey("TournamentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("TournamentGroup");
                });

            modelBuilder.Entity("Domain.Entities.Football.Matches.FootballMatch", b =>
                {
                    b.HasOne("Domain.Entities.Football.Teams.FootballTeam", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Football.Competitions.FootballCompetition", "Competition")
                        .WithMany("Matches")
                        .HasForeignKey("CompetitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Football.Teams.FootballTeam", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Football.Matches.FootballMatch", null)
                        .WithMany()
                        .HasForeignKey("NextMatchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Domain.Entities.Football.Competitions.FootballTournamentGroup", null)
                        .WithMany()
                        .HasForeignKey("TournamentGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.OwnsOne("Domain.ValueObjects.Football.FootballMatchRules", "MatchRules", b1 =>
                        {
                            b1.Property<Guid>("FootballMatchId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("AllowExtraTime")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("MatchRules_AllowExtraTime");

                            b1.Property<bool>("AllowPenaltyShootout")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("MatchRules_AllowPenaltyShootout");

                            b1.Property<int>("ExtraTimeHalfCount")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("MatchRules_ExtraTimeHalfCount");

                            b1.Property<int>("ExtraTimeHalfDurationMinutes")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("MatchRules_ExtraTimeHalfDurationMinutes");

                            b1.Property<int>("HalfDurationMinutes")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(45)
                                .HasColumnName("MatchRules_HalfDurationMinutes");

                            b1.Property<int>("MaxSubstitutions")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(0)
                                .HasColumnName("MatchRules_MaxSubstitutions");

                            b1.Property<int>("NumberOfHalves")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(2)
                                .HasColumnName("MatchRules_NumberOfHalves");

                            b1.Property<int>("PlayersOnField")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer")
                                .HasDefaultValue(11)
                                .HasColumnName("MatchRules_PlayersOnField");

                            b1.Property<bool>("RequireGoalkeeper")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(true)
                                .HasColumnName("MatchRules_RequireGoalkeeper");

                            b1.Property<bool>("RequireOfficialsToStart")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("boolean")
                                .HasDefaultValue(false)
                                .HasColumnName("MatchRules_RequireOfficialsToStart");

                            b1.HasKey("FootballMatchId");

                            b1.ToTable("FootballMatches", "football");

                            b1.WithOwner()
                                .HasForeignKey("FootballMatchId");
                        });

                    b.Navigation("AwayTeam");

                    b.Navigation("Competition");

                    b.Navigation("HomeTeam");

                    b.Navigation("MatchRules")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Football.Matches.FootballMatchEvent", b =>
                {
                    b.HasOne("Domain.Entities.Football.Matches.FootballMatch", null)
                        .WithMany("Events")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Football.Teams.FootballTeam", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Football.Matches.FootballMatchLineupPlayer", b =>
                {
                    b.HasOne("Domain.Entities.Football.Matches.FootballMatch", null)
                        .WithMany("Lineup")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Football.Teams.FootballPlayer", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Football.Matches.FootballPeriodScore", b =>
                {
                    b.HasOne("Domain.Entities.Football.Matches.FootballMatch", null)
                        .WithMany("PeriodScores")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Football.Teams.FootballPlayer", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Football.FootballPositionPreference", "Position", b1 =>
                        {
                            b1.Property<Guid>("FootballPlayerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("PrimaryPosition")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("SecondaryPosition")
                                .HasColumnType("text");

                            b1.HasKey("FootballPlayerId");

                            b1.ToTable("FootballPlayers", "football");

                            b1.WithOwner()
                                .HasForeignKey("FootballPlayerId");
                        });

                    b.Navigation("Position")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Football.Teams.FootballTeamManager", b =>
                {
                    b.HasOne("Domain.Entities.Football.Teams.FootballTeam", null)
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Football.Teams.FootballTeamPlayer", b =>
                {
                    b.HasOne("Domain.Entities.Football.Teams.FootballPlayer", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Football.Teams.FootballTeam", null)
                        .WithMany("Roster")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FootballCompetitionTeam", b =>
                {
                    b.HasOne("Domain.Entities.Football.Competitions.FootballCompetition", null)
                        .WithMany()
                        .HasForeignKey("CompetitionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Football.Teams.FootballTeam", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FootballMatchOfficial", b =>
                {
                    b.HasOne("Domain.Entities.Football.Matches.FootballMatch", null)
                        .WithMany()
                        .HasForeignKey("MatchesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Football.Teams.FootballReferee", null)
                        .WithMany()
                        .HasForeignKey("OfficialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Football.Competitions.FootballTournament", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Football.FootballTournamentRules", "TournamentRules", b1 =>
                        {
                            b1.Property<Guid>("FootballTournamentId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("HasPlayoffStage")
                                .HasColumnType("boolean")
                                .HasColumnName("TournamentRules_HasPlayoffStage");

                            b1.Property<bool>("HasThirdPlaceMatch")
                                .HasColumnType("boolean")
                                .HasColumnName("TournamentRules_HasThirdPlaceMatch");

                            b1.Property<int>("TeamsAdvancingPerGroup")
                                .HasColumnType("integer")
                                .HasColumnName("TournamentRules_TeamsAdvancingPerGroup");

                            b1.HasKey("FootballTournamentId");

                            b1.ToTable("FootballCompetitions", "football");

                            b1.WithOwner()
                                .HasForeignKey("FootballTournamentId");

                            b1.OwnsOne("Domain.ValueObjects.Football.FootballMatchRules", "GroupStageMatchRules", b2 =>
                                {
                                    b2.Property<Guid>("FootballTournamentRulesFootballTournamentId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("AllowExtraTime")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("boolean")
                                        .HasDefaultValue(false)
                                        .HasColumnName("TournamentRules_GroupStage_AllowExtraTime");

                                    b2.Property<bool>("AllowPenaltyShootout")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("boolean")
                                        .HasDefaultValue(false)
                                        .HasColumnName("TournamentRules_GroupStage_AllowPenaltyShootout");

                                    b2.Property<int>("ExtraTimeHalfCount")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasDefaultValue(0)
                                        .HasColumnName("TournamentRules_GroupStage_ExtraTimeHalfCount");

                                    b2.Property<int>("ExtraTimeHalfDurationMinutes")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasDefaultValue(0)
                                        .HasColumnName("TournamentRules_GroupStage_ExtraTimeHalfDurationMinutes");

                                    b2.Property<int>("HalfDurationMinutes")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasDefaultValue(45)
                                        .HasColumnName("TournamentRules_GroupStage_HalfDurationMinutes");

                                    b2.Property<int>("MaxSubstitutions")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasDefaultValue(0)
                                        .HasColumnName("TournamentRules_GroupStage_MaxSubstitutions");

                                    b2.Property<int>("NumberOfHalves")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasDefaultValue(2)
                                        .HasColumnName("TournamentRules_GroupStage_NumberOfHalves");

                                    b2.Property<int>("PlayersOnField")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasDefaultValue(11)
                                        .HasColumnName("TournamentRules_GroupStage_PlayersOnField");

                                    b2.Property<bool>("RequireGoalkeeper")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("boolean")
                                        .HasDefaultValue(true)
                                        .HasColumnName("TournamentRules_GroupStage_RequireGoalkeeper");

                                    b2.Property<bool>("RequireOfficialsToStart")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("boolean")
                                        .HasDefaultValue(false)
                                        .HasColumnName("TournamentRules_GroupStage_RequireOfficialsToStart");

                                    b2.HasKey("FootballTournamentRulesFootballTournamentId");

                                    b2.ToTable("FootballCompetitions", "football");

                                    b2.WithOwner()
                                        .HasForeignKey("FootballTournamentRulesFootballTournamentId");
                                });

                            b1.OwnsOne("Domain.ValueObjects.Football.FootballMatchRules", "PlayoffMatchRules", b2 =>
                                {
                                    b2.Property<Guid>("FootballTournamentRulesFootballTournamentId")
                                        .HasColumnType("uuid");

                                    b2.Property<bool>("AllowExtraTime")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("boolean")
                                        .HasDefaultValue(false)
                                        .HasColumnName("TournamentRules_Playoff_AllowExtraTime");

                                    b2.Property<bool>("AllowPenaltyShootout")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("boolean")
                                        .HasDefaultValue(false)
                                        .HasColumnName("TournamentRules_Playoff_AllowPenaltyShootout");

                                    b2.Property<int>("ExtraTimeHalfCount")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasDefaultValue(0)
                                        .HasColumnName("TournamentRules_Playoff_ExtraTimeHalfCount");

                                    b2.Property<int>("ExtraTimeHalfDurationMinutes")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasDefaultValue(0)
                                        .HasColumnName("TournamentRules_Playoff_ExtraTimeHalfDurationMinutes");

                                    b2.Property<int>("HalfDurationMinutes")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasDefaultValue(45)
                                        .HasColumnName("TournamentRules_Playoff_HalfDurationMinutes");

                                    b2.Property<int>("MaxSubstitutions")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasDefaultValue(0)
                                        .HasColumnName("TournamentRules_Playoff_MaxSubstitutions");

                                    b2.Property<int>("NumberOfHalves")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasDefaultValue(2)
                                        .HasColumnName("TournamentRules_Playoff_NumberOfHalves");

                                    b2.Property<int>("PlayersOnField")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer")
                                        .HasDefaultValue(11)
                                        .HasColumnName("TournamentRules_Playoff_PlayersOnField");

                                    b2.Property<bool>("RequireGoalkeeper")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("boolean")
                                        .HasDefaultValue(true)
                                        .HasColumnName("TournamentRules_Playoff_RequireGoalkeeper");

                                    b2.Property<bool>("RequireOfficialsToStart")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("boolean")
                                        .HasDefaultValue(false)
                                        .HasColumnName("TournamentRules_Playoff_RequireOfficialsToStart");

                                    b2.HasKey("FootballTournamentRulesFootballTournamentId");

                                    b2.ToTable("FootballCompetitions", "football");

                                    b2.WithOwner()
                                        .HasForeignKey("FootballTournamentRulesFootballTournamentId");
                                });

                            b1.Navigation("GroupStageMatchRules")
                                .IsRequired();

                            b1.Navigation("PlayoffMatchRules")
                                .IsRequired();
                        });

                    b.Navigation("TournamentRules")
                        .IsRequired();
                });

            modelBuilder.Entity("Domain.Entities.Football.Competitions.FootballCompetition", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("Domain.Entities.Football.Competitions.FootballCompetitionDivision", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Domain.Entities.Football.Competitions.FootballTournamentGroup", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("Domain.Entities.Football.Matches.FootballMatch", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Lineup");

                    b.Navigation("PeriodScores");
                });

            modelBuilder.Entity("Domain.Entities.Football.Teams.FootballTeam", b =>
                {
                    b.Navigation("Roster");
                });

            modelBuilder.Entity("Domain.Entities.Football.Competitions.FootballTournament", b =>
                {
                    b.Navigation("Groups");
                });
#pragma warning restore 612, 618
        }
    }
}
