// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Domain.Entities.Common;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace MyLeague.Infrastructure.Persistence.Configurations.Common
{
    public class PageContentConfiguration : IEntityTypeConfiguration<PageContent>
    {
        public void Configure(EntityTypeBuilder<PageContent> builder)
        {
            // Set the primary key
            builder.HasKey(n => n.Id);

            // Id - required, not generated by the database
            builder.Property(n => n.Id)
                .IsRequired()
                .ValueGeneratedNever();

            // PageSlug - required, max length 100, unique
            builder.Property(n => n.PageSlug)
                .IsRequired()
                .HasMaxLength(100);
            // Unique index on PageSlug
            builder.HasIndex(n => n.PageSlug)
                .IsUnique();

            // Title - required, max length 200
            builder.Property(n => n.Title)
                .IsRequired()
                .HasMaxLength(200);

            // ContentHtml - required, unlimited length
            builder.Property(n => n.ContentHtml)
                .IsRequired()
                .HasColumnType("text");
            // LastModifiedBy - optional, max length 100
            builder.Property(n => n.LastModifiedBy)
                .HasMaxLength(100);
        }
    }
}
